ndlib/sipity

app/models/sipity/models/group.rb, app/models/sipity/models/permission.rb
I want to expand on the purpose of the Permission model and thoughts
behind it.
[skip ci]
=> Amending documentation to include commentary

app/policies/sipity/policies/sip_policy.rb, app/repositories/sipity/queries/permission_queries.rb, spec/policies/sipity/policies/sip_policy_spec.rb, spec/repositories/sipity/queries/permission_queries_spec.rb
I want to better reflect the method signature, so the method should
be renamed. Besides, I was calling it, and wondering why it wasn't
quite behaving.
=> Renaming method

app/models/sipity/models/group.rb, app/models/user.rb, spec/models/sipity/models/group_spec.rb, spec/models/user_spec.rb
In order to improve clarity of the code, I'm adding these
associations. Given the repository objects, that is the preferred
method for interaction.
=> Adding explicit polymorphic association

app/conversions/sipity/conversions.rb, app/conversions/sipity/conversions/convert_to_permanent_uri.rb, app/conversions/sipity/conversions/convert_to_polymorphic_type.rb, app/conversions/sipity/conversions/convert_to_year.rb, spec/conversions/sipity/conversions/convert_to_permanent_uri_spec.rb, spec/conversions/sipity/conversions/convert_to_polymorphic_type_spec.rb, spec/conversions/sipity/conversions/convert_to_year_spec.rb
As code is an ongoing conversation, I want to make sure that we have
an ever improving understanding on both objects and concepts.
=> Improving documentation on Conversion concept

app/repositories/sipity/repository.rb, spec/repositories/sipity/repository_spec.rb
With commit sipity@50a0644, this method has been implemented.
=> Removing vestigal method

CONTRIBUTING.md
=> Adding contributing instructions for docs

artifacts/permission_model.md
=> Augmenting the Permission Model documents

Gemfile, Gemfile.lock
Making sure that we have the mysql2 gem ready for when we deploy to
a non-development environment.
=> Preparing for a production database

scripts/team-progress
I want to continue to celebrate the work our team is accomplishing.
There are additional stats that can be generated, but those require
stashing changes and checking out different branches.
[skip ci]
=> Adding a script to generate team progress

Gemfile, Gemfile.lock, README.md
> Dragonfly is a framework that enables on-the-fly processing for any
> content type. It is especially suited to image handling. Its uses
> range from image thumbnails to standard attachments to on-demand
> text generation.
>
> https://rubygems.org/gems/dragonfly
$ bundle
=> Adding Dragonfly gem

app/decorators/sipity/decorators/sip_decorator.rb, app/forms/sipity/forms/create_sip_form.rb, app/views/sipity/controllers/sips/new.html.erb, spec/decorators/sipity/decorators/sip_decorator_spec.rb, spec/features/sipity/create_minimum_viable_sip_spec.rb, spec/forms/sipity/forms/create_sip_form_spec.rb, spec/repositories/sipity/queries/sip_queries_spec.rb
We need to prompt the user to select an applicable work type.
=> Adding work_types to create sip form

app/decorators/sipity/decorators/sip_decorator.rb, app/forms/sipity/forms/create_sip_form.rb, app/models/sipity/models/transient_answer.rb, app/repositories/sipity/commands/sip_commands.rb, app/views/sipity/controllers/sips/new.html.erb, spec/decorators/sipity/decorators/sip_decorator_spec.rb, spec/forms/sipity/forms/create_sip_form_spec.rb, spec/repositories/sipity/commands/sip_commands_spec.rb
This is composed of a few commits to highlight the process of stepping towards a solution:
* Capturing the AccessRights answer for the form
* Extracting methods from decorator to form
* Allowing choice of a Sip's access rights answer
* Exposing CreateSipForm#access_rights_answer
=> Exposing access rights transient answer

app/state_machines/sipity/state_machines/etd_student_submission.rb, artifacts/etd-submission-state-machine.dot, spec/state_machines/sipity/state_machines/etd_student_submission_spec.rb
In preparation for meeting with the Grad School, I wanted to make sure
the work flow is properly captured.
=> Updating ETD Submission State Flow

app/models/sipity/models/work.rb
=> Remove SIP references

app/views/sipity/controllers/works/show.html.erb
Adding place holder for describing and attaching things to the ETD.
This is very much an ETD-centric solution, but for now is what we are
working on.
=> Amending Show page based on wireframes

README.md
I want to continue to explain the relationship between these objects
that may not be proper citizens in many peoples minds. The new idea,
a Form object, is perhaps not as clear.
[skip ci]
=> Documenting Forms/Models/Decorators relationship

db/migrate/20150114161600_amend_sipity_additional_attributes_value.rb, db/schema.rb
This is not quite adequate as we may need to say how each predicate
maps/serializes. But I'm making more room for the information.
=> Expanding additional attribute storage space

app/decorators/sipity/decorators/entity_enrichment_action.rb, spec/decorators/sipity/decorators/entity_enrichment_action_spec.rb
Responsible for exposing the necessary information for rendering an
enrichment action (i.e. attach a file, describe the work)
=> Adding EntityEnrichmentAction concept

README.md
For our initial launch, these will be tracked elsewhere.
https://docs.google.com/a/nd.edu/document/d/1gQ_J_nARdDY2OYJJ9kjgXtEDTaph-QdCtT_oD2FdeSc/edit#heading=h.b6hkbwba9zo
[skip ci]
=> Removing TODO items

app/controllers/sipity/controllers/work_enrichments_controller.rb, app/forms/sipity/forms/attach_files_to_work_form.rb, app/models/sipity/models/attachment.rb, app/repositories/sipity/queries/description_queries.rb, app/runners/sipity/runners/work_enrichment_runners.rb, app/views/sipity/controllers/work_enrichments/edit.html.erb, config/routes.rb, spec/controllers/sipity/controllers/work_enrichments_controller_spec.rb, spec/features/sipity/create_minimum_viable_work_spec.rb, spec/forms/sipity/forms/attach_files_to_work_form_spec.rb, spec/models/sipity/models/attachment_spec.rb, spec/repositories/sipity/queries/description_queries_spec.rb, spec/runners/sipity/runners/work_enrichment_runners_spec.rb, spec/support/site_prism_support.rb
This pull request has lots of disparate concerns; Sorry about the confusion.
=> Dltp 347 add action and html form for describing etds

CONTRIBUTING.md, Rakefile, lib/tasks/sipity.rake
This task is destructive in that it will drop the database and rebuild
a fresh database with the correct schema for your working branch. Then
it will go ahead and create a user based on your machine's ENV['USER']
[skip ci]
=> Adding `bootsrap` rake task

app/runners/sipity/runners/citation_runners.rb, app/views/sipity/controllers/citations/new.html.erb, app/views/sipity/controllers/dois/assign_a_doi.html.erb, app/views/sipity/controllers/dois/doi_not_assigned.html.erb, app/views/sipity/controllers/dois/request_a_doi.html.erb, app/views/sipity/controllers/works/edit.html.erb, app/views/sipity/controllers/works/new.html.erb, config/locales/en.yml
Decorating form inputs and adding panels to citation form.
=> Panel refinement

app/repositories/sipity/commands/work_commands.rb, db/migrate/20150204172806_adding_column_constraint_to_attachment.rb, db/schema.rb, spec/repositories/sipity/commands/work_commands_spec.rb, spec/support/sipity/command_repository_interface.rb
Okay, I lie, it is using UUIDs instead of NOIDs from the NOID client.
Related to DLTP-363
=> Adding rudimentary PID Minting service

app/assets/stylesheets/framework_and_overrides.css.scss, app/assets/stylesheets/modules/_action_listing.css.scss, app/assets/stylesheets/modules/_panel.css.scss, app/assets/stylesheets/modules/_visibility.css.scss, app/assets/stylesheets/modules/_work_tasks.css.scss, app/views/sipity/controllers/works/show.html.erb, config/locales/en.yml
@jeremyf it would be nice to have a #done? to style with on the todo items.
=> First pass at styling action items

app/models/sipity/models/role.rb, spec/models/sipity/models/role_spec.rb, spec/repositories/sipity/queries/processing_queries_spec.rb
It may be feasible to not have Role-based symbols, but for now I'm
erring on the side of aggressive control.
=> Adding controlled Role name vocabulary

app/models/sipity/models/processing/strategy_action.rb, db/migrate/20150206173110_adding_action_type_to_action_processing.rb, db/schema.rb, db/seeds.rb, spec/models/sipity/models/processing/strategy_action_spec.rb
Given that we want to be able to segment where/how actions are
rendered on the page, I want a means of identifying their various
meanings. This is that initial attempt.
=> Adding action_type with defaults

app/forms/sipity/forms/work_enrichments/collaborator_form.rb
=> Adding commentary concerning collaborator

app/models/sipity/models/collaborator.rb, app/validators/net_id_validator.rb, spec/models/sipity/models/collaborator_spec.rb, spec/validators/net_id_validator_spec.rb
Adding validator that return true - Enhance with actual code to validate the netid
Adding spec for the validator
Include it as part of collaborator netid validation
=> DLTP-366 Adding netid validator

Gemfile, Gemfile.lock, app/services/sipity/services/ldap_client.rb, spec/services/sipity/services/ldap_client.rb
=> LdapClient

app/assets/stylesheets/framework_and_overrides.css.scss, app/assets/stylesheets/modules/_action_listing.css.scss, app/assets/stylesheets/modules/_attributes.css.scss, app/assets/stylesheets/modules/_messages.css.scss, app/assets/stylesheets/modules/_work_tasks.css.scss, app/views/sipity/controllers/works/show.html.erb, config/locales/en.yml
Reworking the work show page to more closely represent a todo list.
Refinements to action buttons and notifications.
=> Todo list style

app/runners/sipity/runners/work_enrichment_runners.rb
Note: There is an underlying conversion that is happening so I'm
opting to replace that.
=> Replacing :submit? with :enrichment_type

app/assets/stylesheets/modules/_messages.css.scss, app/forms/sipity/forms/create_work_form.rb, app/views/sipity/controllers/works/show.html.erb, config/locales/en.yml, config/locales/simple_form.en.yml, spec/features/sipity/enriching_a_work_spec.rb
Refining the labels and messages used during the initial creation of a work.
=> More internationalization

app/forms/sipity/forms/work_enrichments/defense_date_form.rb, app/views/sipity/controllers/work_enrichments/defense_date.html.erb, config/locales/en.yml
Refining the views for the defense date form
=> Defense date views

app/assets/stylesheets/framework_and_overrides.css.scss, app/decorators/sipity/decorators/processing/enrichment_action_decorator.rb, app/views/sipity/controllers/works/show.html.erb
Now that we have more than one work type there needs to be a slight adjustment to the labeling logic.
=> Fix work type display

app/conversions/sipity/conversions.rb
Concerning Conversions:
> ## Why Conversions?
>
> Sipity is comprised of several sub-systems. The Processing subsystem
> is something that I envision extracting at a future date. However,
> the forms and data capture servcies need to interact with those
> subsystems in a predictable way.
>
> So, in order to ease moving across various boundaries, I'm opting to
> use conversion modules. These modules expose the means of
> transforming (or denying the transformation) an object into another
> type. In other words they document how one object can map to another
> object.
[skip ci]
=> Wordsmithing

app/views/sipity/controllers/dashboards/index.html.erb, app/views/visitors/index.html.erb
Making the dashboard look nicer as we will be exposing it.
=> Dashboard view

app/forms/sipity/forms/create_work_form.rb, app/forms/sipity/forms/etd/advisor_signoff_form.rb, app/mailers/sipity/mailers/email_notifier.rb, app/repositories/sipity/queries/processing_queries.rb, spec/forms/sipity/forms/etd/advisor_signoff_form_spec.rb, spec/mailers/sipity/mailers/email_notifier_spec.rb
These were parts that were missing as I stepped through the particular
behavior.
=> Updating code based on walkthrough

app/decorators/sipity/decorators/processing/resourceful_action_decorator.rb, config/locales/en.yml
Pulling in relevant bits from #182
=> Work delete refinements

app/forms/sipity/forms/manage_account_profile_form.rb, app/repositories/sipity/command_repository.rb, app/repositories/sipity/commands/account_profile_commands.rb, spec/forms/sipity/forms/manage_account_profile_form_spec.rb, spec/repositories/sipity/commands/account_profile_commands_spec.rb, spec/support/sipity/command_repository_interface.rb
@5e2b2587523677dd0b3d471a3706753dfb63a9bc
Responsible for updating a given user's AccountProfile information.
@2b3eda8b4705406fd109188fbc28844ef2cdb904
Responsible for exposing a means of updating a given account's
profile information.
=> Adding account profile

app/conversions/sipity/conversions/extract_input_date_from_input.rb, app/forms/sipity/forms/work_enrichments/defense_date_form.rb, spec/conversions/sipity/conversions/extract_input_date_from_input_spec.rb
@85cf46d60f4972eb7f0b470f4a3d0a196a0e0040
Because I am doing this logic in multiple places, I want to make a
consistent method to handle these extractions.
@0468f63a6a93653324d2078eaab0121103a9ffb8
Making use of the generalized case instead of a conversion that has
little to do with the logic.
=> Extracting method

app/decorators/sipity/decorators/email_notification_decorator.rb, app/mailers/sipity/mailers/email_notifier.rb, app/repositories/sipity/queries/work_queries.rb, app/views/sipity/mailers/email_notifier/confirmation_of_entity_submitted_for_review.html.erb, app/views/sipity/mailers/email_notifier/confirmation_of_grad_school_signoff.html.erb, spec/decorators/sipity/decorators/email_notification_decorator_spec.rb, spec/mailers/sipity/mailers/email_notifier_spec.rb, spec/repositories/sipity/queries/work_queries_spec.rb, spec/support/sipity/command_repository_interface.rb
This pull request is specifically address confirmation_of_entity_submitted_for_review
=> Working on email decorators

app/models/sipity/models/collaborator.rb, app/models/sipity/models/processing/actor.rb, app/models/sipity/models/role.rb
=> Clarifying Actor/Role/Collaborator

app/forms/sipity/forms/etd/advisor_requests_change_form.rb, app/forms/sipity/forms/etd/advisor_signoff_form.rb, app/forms/sipity/forms/etd/grad_school_requests_change_form.rb, app/forms/sipity/forms/etd/grad_school_signoff_form.rb, app/forms/sipity/forms/etd/submit_for_review_form.rb, app/forms/sipity/forms/state_advancing_action.rb
There was a lot of duplication, which added to the chatter of the
application. Removing that in preference for a common ancestor.
=> Extracting a common ancestor

app/forms/sipity/forms/etd/submit_for_review_form.rb, app/views/sipity/controllers/work_event_triggers/new.html.erb, config/locales/en.yml, spec/forms/sipity/forms/etd/submit_for_review_form_spec.rb
This pull request is primarily concerned with UI for the submit_for_review state transition.
=> Refining state transition view

.travis.yml, Gemfile, Gemfile.lock, README.md, spec/coverage_helper.rb
As the Coveralls badge was not showing up on Github, I want to see if
CodeClimate will.
=> Switching to Code Climate code coverage

app/forms/sipity/forms/work_enrichments/attach_form.rb
Strong Parameters are an excellent idea; Though they smell of
inappropriate abstraction. However, they are yet another guard against
nefarious actors wanting to inject problems into our world.
Prior to this change updating attachments breaks down.
=> Coping with Strong Parameters

spec/runners/sipity/runners/base_runner_spec.rb
I want to make sure the default authentication layer is being
executed.
=> Changing `allow` to `expect`

app/assets/stylesheets/modules/_messages.css.scss, app/views/layouts/_messages.html.erb, config/locales/en.yml
Filling out missing messages and keeping the alert display consistent.
=> Alert refinements

app/assets/stylesheets/modules/_attributes.css.scss
I'm leaving the door open for ordered lists at some point.
=> Multi-value attribute styling

app/forms/sipity/forms/work_enrichments/access_policy_form.rb, spec/forms/sipity/forms/work_enrichments/access_policy_form_spec.rb
As I was working through the application, I encountered a problem
related to a blank copyright being acceptable. This, I believe,
resolves that issue.
=> Tweaking copyright calculation

config/locales/en.yml
These terms were extracted from the terms of service for the current
ETD application. http://etd.nd.edu/ETD-db/ETD-submit/enter_title_page
Closes #253
=> Updating terms of deposit as per previous system

app/forms/sipity/forms/etd/advisor_requests_change_form.rb, app/forms/sipity/forms/etd/respond_to_advisor_request_form.rb, app/forms/sipity/forms/etd/respond_to_grad_school_request_form.rb, config/locales/en.yml, db/seeds.rb, spec/forms/sipity/forms/etd/advisor_requests_change_form_spec.rb, spec/forms/sipity/forms/etd/respond_to_advisor_request_form_spec.rb, spec/forms/sipity/forms/etd/respond_to_grad_school_request_form_spec.rb
@ea14a030eb014457de5e3bc974ad68ebde760047
Related to #266
@10b24348296f280105b3ac109f047f7f69124065
@1ca6c65bb58fc803db5fc1348bd60df1e2d71e9f
@d9819dbbd7f124222c279344580b285b75ecefe6
@0b93544fab584dfae276c204b5d8bcfe5075f90f
@78cb09d5fe52692590e5608da600a72f414e309c
Closes #266
=> Issue 266 amending state diagram

app/assets/stylesheets/framework_and_overrides.css.scss, app/views/layouts/_messages.html.erb, app/views/pages/about.html.erb, app/views/sipity/controllers/works/show.html.erb, config/initializers/high_voltage.rb, config/locales/en.yml, spec/features/visitors/about_page_spec.rb
=> About page

app/models/sipity/models/collaborator.rb, spec/forms/sipity/forms/work_enrichments/collaborator_form_spec.rb, spec/models/sipity/models/collaborator_spec.rb, spec/repositories/sipity/commands/work_commands_spec.rb, spec/repositories/sipity/queries/collaborator_queries_spec.rb, spec/repositories/sipity/queries/processing_queries_spec.rb, spec/services/sipity/services/doi_creation_request_metadata_gatherer_spec.rb
=> Change role texts for Collaborators

app/models/sipity/models/processing/strategy_action.rb, db/seeds.rb, spec/models/sipity/models/processing/strategy_action_spec.rb
Being able to run `rake db:seed` multiple times without damaging
side effect is a bit challenging.
Closes #299
=> Fixing database seeding process

app/assets/stylesheets/framework_and_overrides.css.scss, app/assets/stylesheets/modules/_tables.css.scss, app/views/sipity/controllers/works/show.html.erb, config/locales/en.yml
Minor style and notification refinements.
=> Housekeeping

Gemfile, Gemfile.lock, config/application.yml, config/initializers/dragonfly.rb
=> configure dragonfly-s3 for prod/pprd

app/forms/sipity/forms/work_enrichments/access_policy_form.rb, app/models/sipity/models/simple_controlled_vocabulary.rb, app/repositories/sipity/queries/simple_controlled_vocabulary_queries.rb, app/views/sipity/controllers/work_enrichments/access_policy.html.erb, db/seeds.rb, spec/forms/sipity/forms/work_enrichments/access_policy_form_spec.rb, spec/repositories/sipity/queries/simple_controlled_vocabulary_queries_spec.rb, spec/support/sipity/command_repository_interface.rb, spec/support/sipity/query_repository_interface.rb
=> Issue 305 copyright controlled vocab

app/forms/sipity/forms/work_enrichments/collaborator_form.rb, spec/forms/sipity/forms/work_enrichments/collaborator_form_spec.rb
=> Updating collaborator validation

Gemfile, Gemfile.lock, app/repositories/sipity/commands/work_commands.rb, app/services/sipity/services/noid_minter.rb, config/application.rb, config/application.yml, config/environments/development.rb, config/environments/test.rb, config/initializers/figaro.rb, spec/services/sipity/services/noid_minter_spec.rb
=> Issue 256 - Pid minter service

app/mailers/sipity/mailers/email_notifier.rb, app/views/sipity/mailers/email_notifier/respond_to_advisor_request.html.erb, app/views/sipity/mailers/email_notifier/respond_to_grad_school_request.html.erb
> Given that an advisor can request a change from a grad student
> When the grad student submits their response to that change
> Then the advisor should receive that response
Closes #324
> Given that the grad school can request a change from a grad student
> When the grad student submits their response to that change
> Then the grad school should receive that response
Closes #325
=> Add respond to request for change

app/assets/stylesheets/framework_and_overrides.css.scss, app/views/sipity/controllers/account_profiles/edit.html.erb, config/locales/en.yml
Note that the terms of service are copied verbatim from CurateND. They
may need some adjustments for this context.
=> Refining account creation screen.

app/services/sipity/services/apply_access_policies_to.rb, spec/services/sipity/services/apply_access_policies_to_spec.rb
```gherkin
Given I have created a work
When I go to update the policy form
Then the updates are not persisted
```
Closes #343
=> Ensuring access policies are updated

config/application.yml, config/environments/pre_production.rb, config/environments/production.rb, config/environments/staging.rb, config/initializers/ezid_client_initializer.rb, config/secrets.yml
* Alphabetizing keys
* Removing some uses of the secrets.yml (Don't like it; Bleck!)
=> Tidying up configuration management

config/deploy/production.rb
=> Updating production deploy environment

app/decorators/sipity/decorators/processing/processing_comment_decorator.rb, app/decorators/sipity/decorators/work_decorator.rb, app/repositories/sipity/queries/comment_queries.rb, app/repositories/sipity/query_repository.rb, app/views/sipity/controllers/works/show.html.erb, spec/decorators/sipity/decorators/work_decorator_spec.rb, spec/repositories/sipity/queries/comment_queries_spec.rb, spec/support/sipity/command_repository_interface.rb, spec/support/sipity/query_repository_interface.rb
=> Display comments

CONTRIBUTING.md, scripts/start-issue
See the comments in the various scripts.
[skip ci]
=> Wordsmithing CONTRIBUING & ./scripts/start-issue

CONTRIBUTING.md
These are some of the expectations that I have internalized, but I
want to state them clearly and articulate why I believe they should be
part of the policy regarding our build.
[skip ci]
=> Articulating expectations regarding code

app/conversions/sipity/conversions/convert_to_registered_action.rb, app/conversions/sipity/conversions/convert_to_work.rb, app/repositories/sipity/queries/processing_queries.rb, app/services/sipity/services/remote_netid_validator.rb
There several yard based warnings when generating documentation. This
pull request addresses those warnings.
[skip ci]
=> Revising documentation warnings

app/forms/sipity/forms/work_enrichments/attach_form.rb
=> Correction in conditional statement

app/forms/sipity/forms/work_enrichments/attach_form.rb
The removed private method was untested and duplicating an existing
process.
=> Removing duplication of knowledge/processing

scripts/rebuild-erd
=> Adding script to rebuild ERD

db/migrate/20150410193943_expanding_work_title_to_text.rb, db/schema.rb
=> Altering Works#title to be text

Gemfile.lock
@6925d866c3340b197ca89bcb2d7cce5fffb2519b
```console
$ bundle update jbuilder
```
@3d3c63f1bf8ef640c2d69ac27eb4f85dfbb27bfe
```console
$ bundle update execjs
```
@4bf3faa7c90541daafe298e2ab77bd5a08981c71
```console
$ bundle update autoprefixer-rails
```
=> Updating depdendencies

Gemfile, Gemfile.lock, Rakefile, config/database.yml, db/schema.rb
I have encountered two issues with the differences between mysql and
sqlite. I want to make sure that we are vetting those differences in
development so they do not show up in staging.
One issue was the index length of a text field. Sqlite doesn't care
and Mysql needs a length specified. The other issue is since forgetten
by me.
=> Switching to mysql2 for testing and development

config/application.yml, config/initializers/figaro.rb, config/secrets.yml
Instead of keys that look like they are real, ensuring things look
fake; Because they are. We hold the keys elsewhere.
For the good @dbrower's sanity.
=> Clarifying that existing keys are not real

.yardopts, Gemfile, Gemfile.lock
This helps improve the documentation by adding automatic information
regarding relationships and delegation.
see https://github.com/theodorton/yard-activerecord
=> Adding auto-docing module ActiveRecord relations

app/models/sipity/models/processing/strategy_action.rb, app/models/sipity/models/processing/strategy_state.rb
I was hesitant to include these as they were crossing what I
considered boundaries; However the ERD is more complete when these
items are present.
=> Adding potential missing relationships

README.md
Answer Why do some repository methods delegate to a service object and
other methods have inline behavior?
[skip ci]
=> Updating README with explanation of Form/Services

CODE_OF_CONDUCT.md, CONTRIBUTING.md
=> Adding a project code of conduct

app/decorators/sipity/decorators/emails/processing_comment_decorator.rb, app/decorators/sipity/decorators/emails/registered_action_decorator.rb
=> Rich text sanitization

app/data_generators/sipity/data_generators/etd/work_types_processing_generator.rb, app/models/sipity/models/processing/entity.rb, db/seeds/groups_and_roles_seeds.rb, spec/data_generators/sipity/data_generators/etd/submission_window_processing_generator_spec.rb, spec/data_generators/sipity/data_generators/etd/work_types_processing_generator_spec.rb, spec/data_generators/sipity/data_generators/find_or_create_submission_window_spec.rb, spec/data_generators/sipity/data_generators/find_or_create_work_area_spec.rb, spec/data_generators/sipity/data_generators/find_or_create_work_type_spec.rb, spec/models/sipity/models/processing/entity_spec.rb
@fcde0e55b0dd23c34bfcc609eb87b7cddf8c22e1
@b14ebbb9763940109e47b990b4c57c27bdd2d820
Demonstrating that I won't keep creating and/or updating data if I
call this script.
@8daa45217a963c02af12e3113c89b1ac6d54a7ef
Demonstrating that I won't keep creating and/or updating data if I
call this script.
@a0573b889d2a79bef63e83ab6f186b82d463cc63
Demonstrating that I won't keep creating and/or updating data if I
call this script.
@89501f62514e490bd6284c31d1fa9c1222659979
Demonstrating that I won't keep creating and/or updating data if I
call this script.
@7b20a19207460b0808af621687d2e36dc0171bac
Demonstrating that I won't keep creating and/or updating data if I
call this script.
=> Working on etd submission window generator

app/forms/sipity/forms/submission_window_forms.rb, app/repositories/sipity/queries/submission_window_queries.rb, spec/forms/sipity/forms/submission_window_forms_spec.rb, spec/repositories/sipity/queries/submission_window_queries_spec.rb, spec/support/sipity/command_repository_interface.rb, spec/support/sipity/query_repository_interface.rb
In preparation for the ULRA work form retrieval normalizing the
underlying elements.
=> Retrieving dynamic SubmissionWindow forms

app/forms/sipity/forms/ulra/start_a_submission_form.rb, app/views/sipity/controllers/submission_windows/start_a_submission.html.erb, spec/forms/sipity/forms/ulra/start_a_submission_form_spec.rb
=> Exposing required attributes for ULRA Start

app/forms/sipity/forms/etd/start_a_submission_form.rb, app/forms/sipity/forms/ulra/start_a_submission_form.rb, spec/forms/sipity/forms/etd/start_a_submission_form_spec.rb, spec/forms/sipity/forms/ulra/start_a_submission_form_spec.rb
I need work areas for the submission forms. How to address that?
=> Ensuring that StartASubmission can be converted

app/assets/javascripts/vendor/redactor.js
Now you can tab out of the text box.
=> Removing the tabifier behavior

app/forms/sipity/forms/processing_form.rb, spec/forms/sipity/forms/processing_form_spec.rb
See updated documentation for further reference.
[skip ci]
=> Updating documentation concerning ProcessingForm

artifacts/uncalled-method-check.results.csv, scripts/uncalled-method-check
@de74f97cb2f69df48a962766a8dd22e1cb8d996e
Lots of things happen in config, lets see how things are going.
[skip ci]
@08c923166544274b23531cf8065a4d6c8820f863
Leveraging changes from the following pull requests:
* seattlerb/debride#19
* seattlerb/debride#18
*I had to build a local version of the debride gem with these
changes.*
[skip ci]
=> Amending uncalled method check

Gemfile
> Your Gemfile lists the gem mysql2 (>= 0) more than once.
> You should probably keep only one of them.
=> Addressing bundle warning:

config/deploy.rb
The dog and pony show is something that only happens in Staging.
[skip ci]
=> Removing ability to reset dog and pony show

config/locales/en.yml
=> Tidying up language for degree and program name

config/application.rb
As per Ernie Miller's blog post, removing some of the extraneous
generated files from a `rails generate` command.
http://erniemiller.org/2015/06/16/rails-application-rb-recommendations/
[skip ci]
=> Removing some auto-generated cruft

Gemfile, Gemfile.lock
@91601bdddd0ebd8d430208ed10f21f5dbc431974
$ ./script/update-dependency autoprefixer-rails
@9efda9b6c75ed929c666b926637aa80c1ccbc9b8
=> Updating dependencies

Gemfile, Gemfile.lock, app/data_generators/sipity/data_generators/work_types/self_deposit_generator.rb, app/forms/sipity/forms/work_submissions/self_deposit/access_policy_form.rb, app/forms/sipity/forms/work_submissions/self_deposit/affiliation_form.rb, app/forms/sipity/forms/work_submissions/self_deposit/attach_form.rb, app/forms/sipity/forms/work_submissions/self_deposit/collaborator_form.rb, app/forms/sipity/forms/work_submissions/self_deposit/describe_form.rb, app/forms/sipity/forms/work_submissions/self_deposit/search_term_form.rb, app/forms/sipity/forms/work_submissions/self_deposit/submit_for_review_form.rb, app/models/sipity/models/additional_attribute.rb, app/views/sipity/controllers/work_submissions/self_deposit/access_policy.html.erb, app/views/sipity/controllers/work_submissions/self_deposit/affiliation.html.erb, app/views/sipity/controllers/work_submissions/self_deposit/attach.html.erb, app/views/sipity/controllers/work_submissions/self_deposit/collaborator.html.erb, app/views/sipity/controllers/work_submissions/self_deposit/describe.html.erb, app/views/sipity/controllers/work_submissions/self_deposit/search_term.html.erb, config/locales/en.yml, spec/forms/sipity/forms/work_submissions/self_deposit/access_policy_form_spec.rb, spec/forms/sipity/forms/work_submissions/self_deposit/affiliation_form_spec.rb, spec/forms/sipity/forms/work_submissions/self_deposit/attach_form_spec.rb, spec/forms/sipity/forms/work_submissions/self_deposit/collaborator_form_spec.rb, spec/forms/sipity/forms/work_submissions/self_deposit/describe_form_spec.rb, spec/forms/sipity/forms/work_submissions/self_deposit/search_term_form_spec.rb, spec/forms/sipity/forms/work_submissions/self_deposit/submit_for_review_form_spec.rb
Note: I am delegating the 'submit' to processing_action_form in collaborator_form for the time being
=> Forms for self-deposit

architecture/collaborators.md
This is a snap shot of my current understanding of Collaborators.
Its meant to give guidance and begin our conversation concerning
collaboration on works and how we capture and persist these various
elements.
[skip ci]
=> Adding collaborators architecture document

Gemfile.lock
$ ./script/update-dependency capybara
=> Updating capybara dependency

Gemfile.lock
=> Updating secondary dependencies

Gemfile.lock
@097e75261a815be8cbcbad77720ea2cd4ddf93e7
$ ./script/update-dependency autoprefixer-rails
@bfee55d0c3ba692c1b0c5ddf8b4dffc253053c3a
$ ./script/update-dependency dragonfly
@85ea363caa078bfaa6848dde4c0fb26f06b87c9a
$ ./script/update-dependency simple_form
@ffd2636c2e5fd6188a7de357955069425dceabc4
```console
$ bundle update
```
=> Updating dependency

.hound.yml, app/data_generators/sipity/data_generators/work_types/etd_generator.rb, app/exporters/sipity/exporters/etd_exporter.rb, app/forms/sipity/forms/work_submissions/etd/submit_for_ingest_form.rb, app/models/sipity/models/role.rb, config/environment_bootstrapper.rb, scripts/etd_export_runner.rb, spec/forms/sipity/forms/work_submissions/etd/submit_for_ingest_form_spec.rb, spec/repositories/sipity/queries/processing_queries_spec.rb
Create user and group for etd batch user
Create appropriate action and permissions
Create SubmitForIngestForm
Create rails runner for etd batch ingester
=> Wrap up etd batch ingester

app/forms/sipity/forms/work_submissions/etd/ingest_with_postponed_cataloging_form.rb, app/models/sipity/models/work.rb, spec/forms/sipity/forms/work_submissions/etd/ingest_with_postponed_cataloging_form_spec.rb, spec/models/sipity/models/work_spec.rb
This was requested by Grad School on 09-29-15
=> Make scheduled_time field optional

Gemfile.lock
$ ./script/update-dependency selenium-webdriver
=> Updating selenium-webdriver dependency

app/forms/sipity/forms/work_submissions/etd/ingest_with_postponed_cataloging_form.rb, spec/forms/sipity/forms/work_submissions/etd/ingest_with_postponed_cataloging_form_spec.rb
=> Date format for schedule time

Gemfile.lock
$ ./script/update-dependency rails_layout
=> Updating rails_layout dependency

app/jobs/sipity/jobs/etd/bulk_ingest_job.rb, spec/jobs/sipity/jobs/etd/bulk_ingest_job_spec.rb
Why:
* Because there are errors that we are encountering regarding ingest
How:
* By capturing the error and moving on
=> Updating error handling for bulk ingest

app/mappers/sipity/mappers/etd_mapper.rb, config/locales/en.yml, spec/mappers/sipity/mappers/etd_mapper_spec.rb
This was omitted from the last round of information.
=> Adding degree level to ETD export

scripts/commands/generate_state_machine_diagrams.rb, scripts/templates/for_state_machines.dot.erb
As I'm working with the state machine, I'm finding it helpful to know
the ID of each of the given states.
[skip ci]
=> Adding state ID to workflow diagram generation

config/locales/en.yml
=> Renaming scheduled time to scheduled date

config/application.yml, config/deploy.rb, config/initializers/devise.rb, config/initializers/figaro.rb
This will let us use different credentials in each environment.
=> Parameterizing CAS configuration

Rakefile, app/data_generators/sipity/data_generators/find_or_create_submission_window.rb
Ensuring that bootstrapping runs with data migrations. There may
be eventual issues with mixing schema load, data generation, and
data migrations. However, for now this appears to work.
[skip ci]
=> Tidying up bootstrapping behavior

app/views/sipity/controllers/work_submissions/ulra/attach.html.erb, app/views/sipity/controllers/work_submissions/ulra/project_information.html.erb, app/views/sipity/controllers/work_submissions/ulra/publisher_information.html.erb, app/views/sipity/controllers/work_submissions/ulra/research_process.html.erb
I couldn’t reproduce the problem @jeremyf is having with checkbox rendering. This _may_ fix it.
=> Fixing panel footer alignment; checkbox refinements

Gemfile.lock, app/forms/sipity/forms/work_submissions/ulra/research_process_form.rb, app/views/sipity/controllers/work_submissions/ulra/research_process.html.erb, spec/forms/sipity/forms/work_submissions/ulra/research_process_form_spec.rb
@20112ba20090cc513562309b5d30cf57fe18ac6e
I'm working on the resources used in research, and need the updates.
@a90bbfc4fe25138a8b6ba9dbd4ff4129fc78cff7
There are several new categories that were provided. I'm breaking them
apart into their constituent groups.
Related to #999
=> Working on library resource update

Gemfile.lock, app/data_generators/sipity/data_generators/work_types/etd_work_types.config.json, app/data_generators/sipity/data_generators/work_types/ulra_work_types.config.json, app/forms/sipity/forms/work_submissions/core/access_policy_form.rb, app/forms/sipity/forms/work_submissions/core/copyright_form.rb, app/forms/sipity/forms/work_submissions/ulra/access_policy_form.rb, app/views/sipity/controllers/work_submissions/core/access_policy.html.erb, app/views/sipity/controllers/work_submissions/core/copyright.html.erb, config/locales/en.yml, db/data/20160128183836_remove_faculty_ability_to_update_access_policy.rb, db/schema.rb, spec/forms/sipity/forms/work_submissions/core/access_policy_form_spec.rb, spec/forms/sipity/forms/work_submissions/core/copyright_form_spec.rb
@9817ee18b254e9d259c42b4e9dafa30d69f0117c
@f1970854f97cb62eccf77bde5c0fe61dc62a8933
As much as we would like these to coexist, its a lot to ask a person to
complete.
@3720ed440bba38c2f02bbd693f9d21132a06e32c
As per email from Julie concerning welcome text.
@6545493cce43e29c9b6fe23460a7b639a5cbfaf5
=> Updates concerning ulra

app/forms/sipity/forms/work_submissions/ulra/attach_form.rb, app/views/sipity/controllers/work_submissions/ulra/attach.html.erb, app/views/sipity/controllers/work_submissions/ulra/faculty_response.html.erb
@ea7ae628b6f78da63f682b539fd1ee19f3700d67
As per the email from Julie V.
@d3b8f09e6d1ddbfa53eb98a9f6effdf682253331
As per Julie's email
@76a260d8eccd5cf845eedf9b1a3ec5fbbaa594ac
=> Updating ulra texts

Gemfile.lock
`$ ./script/update-dependency jbuilder`
=> Updating jbuilder dependency

app/data_generators/sipity/data_generators/work_types/etd_work_types.config.json, app/decorators/sipity/decorators/emails/work_email_decorator.rb, app/mailers/sipity/mailers/etd_mailer.rb, app/views/sipity/mailers/etd_mailer/_assistance_for_grad_students_work_is_done_but_may_have_questions.html.erb, app/views/sipity/mailers/etd_mailer/confirmation_of_grad_school_signoff.html.erb, app/views/sipity/mailers/etd_mailer/hurray_your_work_is_in_curatend.html.erb, app/views/sipity/mailers/etd_mailer/thank_you_for_your_patience_with_the_new_etd_system.html.erb, spec/decorators/sipity/decorators/emails/work_email_decorator_spec.rb
@91634dd25e027e87a6295ac39eff16100abb28a9
We want to communicate to the students that just because the grad
school has approved the work, there is still more to do:
* cataloging
* ingest
This means first, apologizing for a delay in those records that were
submitted but not sent through the rigors. Second explaining that will
receive an email when the cataloging is complete.
@53882074f0a40c94a1955c42fc69593413c74430
=> Updating language for etd

app/data_generators/sipity/data_generators/work_types/etd_work_types.config.json, app/views/sipity/mailers/etd_mailer/confirmation_of_grad_school_signoff.html.erb, app/views/sipity/mailers/etd_mailer/grad_school_requests_cataloging.html.erb, config/locales/en.yml, db/data/20160210204153_remove_grad_school_requests_cataloging_for_action_taken.rb, db/schema.rb
@31eef939f132ddedb9dc26c8d18b8cf121bb8f00
Need to verify that catalogers receive emails when they enter the given
state.
@25722c04121277283348894a4f28d919b12bd86a
@64b2d78e99cb91eb86953af1e452049caf12fee4
@7048b85edeb92b42d989d25427ec5cb2fc139d92
Need to ensure that the Grad School can continue to send the item
forward if it has been sent back.
=> Working on grad school amendments

Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/schedule.rb
@77bf6f2134921dcdc2bcc642c12633c5aa94944d
See https://github.com/javan/whenever
`$ bundle`
@2dc78e87edeb81c7d796dd19ef7342ff7501f2dc
`$ wheneverize .`
@f3de646f65455c9680bcbee21f4317630e9d6428
@ef45a4abe755edeb43d33f4b2b864c28325a40e8
See https://github.com/javan/whenever#capistrano-v3-integration for
more details.
=> Adding whenever gem

spec/config/initializers/power_converters_spec.rb
The boolean convertor will convert gibberish to true. Adding tests so that this behavior is clear.
=> Add more boolean converter tests

app/conversions/sipity/conversions/extract_input_date_from_input.rb
=> Updating documentation

app/data_generators/sipity/data_generators/work_types/etd_work_types.config.json
This allows advisors to continue to see works under grad school review.
=> Stop-gap solution for #1041

app/processing_hooks/sipity/processing_hooks.rb
There were two parameterized method calls back to back. It was a bit
hard to read. By splitting it up, I'm hoping to improve the legibility.
=> Breaking apart method chain

Gemfile.lock
`$ ./script/update-dependency mysql2`
=> Updating mysql2 dependency

Gemfile.lock
`$ ./script/update-dependency locabulary`
=> Updating locabulary dependency

README.md
=> Adding documentation concerning permissions

config/schedule.rb
=> re-enable cron job

Gemfile.lock
=> Updating Locabulary

Gemfile, Gemfile.lock
`$ ./script/update-dependency rof`
=> Updating rof dependency

config/deploy.rb, scripts/update_secrets.sh
This reverts commit f8deb59c80664aa425ad36ced06657ec4c5ee9a4.
=> Revert "Updating the secret deployment process"

app/forms/sipity/forms/work_areas/core/show_form.rb, app/parameters/sipity/parameters/search_criteria_for_works_parameter.rb, app/presenters/sipity/controllers/work_areas/core/show_presenter.rb, app/presenters/sipity/controllers/work_areas/filter_form_presenter.rb, app/presenters/sipity/controllers/work_areas/ulra/work_presenter.rb, app/repositories/sipity/queries/processing_queries.rb, app/repositories/sipity/queries/submission_window_queries.rb, app/repositories/sipity/queries/work_queries.rb, app/views/sipity/controllers/work_areas/ulra/show.html.curly, spec/forms/sipity/forms/work_areas/core/show_form_spec.rb, spec/parameters/sipity/parameters/search_criteria_for_works_parameter_spec.rb, spec/presenters/sipity/controllers/work_areas/core/show_presenter_spec.rb, spec/presenters/sipity/controllers/work_areas/filter_form_presenter_spec.rb, spec/presenters/sipity/controllers/work_areas/ulra/work_presenter_spec.rb, spec/repositories/sipity/queries/processing_queries_spec.rb, spec/repositories/sipity/queries/submission_window_queries_spec.rb, spec/repositories/sipity/queries/work_queries_spec.rb, spec/support/sipity/command_repository_interface.rb, spec/support/sipity/query_repository_interface.rb
ea3e35be7b8b454b904e9e1dcc28f5f453d58a85
From the main work area page, allow for filtering on submission window.
04954de83c339da3b4908cc6d454f4b76066c542
e8883d1ada9bc93082af5679d0e3f947c8ef425b
Need to limit which attributes I can filter on
9bc0c256348be61fc36ce5ad5a483f91fb04639f
The interaction was abusing a Hash structure. By factoring towards a
specific parameter, I'm able to more clearly describe the interaction.
c6eadf3fd1a5282d11a6fb3fe0dd13b029211405
Expected cardinality to be either an integer or :many
9393092e73f3e22042c9a0bc3c2f471763aee5d2
d743effa6bad454193111894e5546c40b2228cd3
=> Ulra modifications

Gemfile.lock
Adding new program names and degrees
* Related to DLTP-1071
* DLTP-1072 # QA
=> Updating Sipity to include Locabulary update

README.md, app/data_generators/sipity/data_generators/work_types/etd_work_types.config.json, app/forms/sipity/forms/work_submissions/etd/banner_program_code_form.rb, app/models/sipity/models/additional_attribute.rb, app/views/sipity/controllers/work_submissions/etd/banner_program_code.html.erb, scripts/commands/generate_state_machine_diagrams.rb, spec/forms/sipity/forms/work_submissions/etd/banner_program_code_form_spec.rb
From [DLTP-1074](https://jira.library.nd.edu/browse/DLTP-1074)
> As the Grad School I want to include a Banner Program Code during my ETD reviews
1cd46d04ad966dfa787970c216fba6c26b17509b
Related to DLTP-1075 #Development
f10d1abc1caff49735a02846b7aa7a1fc3419ed9
Related to DLTP-1075
f73b62847a0cf14295b002abe6247ca81d058a11
Related to DLTP-1075
9fc2a54610335cddebbd7be20392629a7a4b7a35
Related to DLTP-1075
e02a2d7260fe59582f3d66ab45d53eae9e1b11ea
08a91da2d8d1d5efeadf258d4e9c1f9af4cccb04
DLPT-1075
930fb5eeb4f458fcea1f09181330ecd3db52221d
=> Adding Banner Code to ETD work submission

app/data_generators/sipity/data_generators/work_types/ulra_work_types.config.json
Exposing a means for data remediators to update attachments in the
application.
=> Adding data attachment remediation options

README.md, app/data_generators/sipity/data_generators/processing_action_schema.rb, app/data_generators/sipity/data_generators/strategy_permission_schema.rb, app/data_generators/sipity/data_generators/work_type_schema.rb
In an effort to improve documentation and clarify further elements of
the Sipity workflow, I'm describing what each part of the schema is
about.
=> Adding schema documentation to clarify

app/views/sipity/controllers/work_submissions/core/access_policy.html.erb, app/views/sipity/controllers/work_submissions/etd/access_policy.html.erb, config/locales/en.yml, spec/processing_hooks/sipity/processing_hooks/etd/works/access_policy_processing_hook_spec.rb
0958ec23898e93f6dc632ded5018ee25264f3cdb
DLTP-1542
1b43d40adb0f3f177cefede697d879f10be4516b
Based on https://github.com/ndlib/sipity/pull/1183 feedback, I'm
updating to replace the language around restricted/registered with
"ND only".
DLTP-1542
=> Relabeling "Open Access" to "Public"

app/jobs/sipity/jobs/core/bulk_ingest_job.rb, spec/jobs/sipity/jobs/core/bulk_ingest_job_spec.rb
Fix batch ingest jobs error handling.
=> Fix parameters send to Sentry

Gemfile, Gemfile.lock
In working on upgrading CurateND, I found it helpful to have
alphabetized gem declarations.
=> Alphabetizing gem declarations

Gemfile.lock
Github alerted me to the following [vulnerability][1]. To resolve the
vulnerability, I ran the following:
```console
$ bundle update yard
```
[1]:https://github.com/lsegal/yard/security/advisories/GHSA-xfhh-rx56-rxcr
=> Updating yard dependency

README.md
This is my best recollection on how to get up and running from a base
OSX install.
=> Adding documentation to run locally

Gemfile, Gemfile.lock
Curate-213
The Center for Network and Data Science (CNDS) and the Center for Social Science Research (CSSR) are becoming the Lucy Family Institute for Data and Society.
=> Update admin unit

app/controllers/sipity/controllers/work_submission_callbacks_controller.rb, app/forms/sipity/forms/work_submissions/core/ingest_completed_form.rb
211b08b510f8a75ebcbb3df7bff218b4359c3a58
e964c2237d1365f76cf4f507b4c40b1660563d05
=> Wordsmithing documentation

Gemfile, Gemfile.lock
=> Update locabulary for CDS

app/views/sipity/mailers/etd_mailer/_grad_school_email_signature.html.erb
=> Update Grad School mailing address signature

app/exporters/sipity/exporters/batch_ingest_exporter.rb
=> bug: curate-318 change default sipity ingest workflow

app/forms/sipity/forms/work_submissions/etd/request_change_on_behalf_of_form.rb, app/forms/sipity/forms/work_submissions/etd/signoff_on_behalf_of_form.rb, app/presenters/sipity/controllers/translation_assistant.rb, config/locales/en.yml, spec/forms/sipity/forms/work_submissions/etd/request_change_on_behalf_of_form_spec.rb, spec/forms/sipity/forms/work_submissions/etd/signoff_on_behalf_of_form_spec.rb
Completes https://jira.library.nd.edu/browse/CURATE-104
Screencaps shown below.
=> Clarify advisor text

app/exporters/sipity/exporters/base_exporter/api_file_utils.rb, spec/exporters/sipity/exporters/base_exporter/api_file_utils_spec.rb
=> Log Restclient errors

app/exporters/sipity/exporters/base_exporter/api_file_utils.rb
Sentry expects to receive an exception.
Fixes DAS-3026
=> Send correct type of object to Sentry
