spec/mailers/sipity/mailers/email_notifier_spec.rb

DEPRECATION WARNING: `#deliver` is deprecated and will be removed in
Rails 5. Use `#deliver_now` to deliver immediately or `#deliver_later`
to deliver through Active Job. (called from block (3 levels) in
<module:Mailers> at ./sipity/spec/mailers/sipity/mailers/email_notifier_spec.rb:17)

Removing deprecation warning

---

app/conversions/sipity/conversions/convert_to_polymorphic_type.rb
app/exceptions/sipity/exceptions.rb
app/repositories/sipity/queries/permission_queries.rb
spec/conversions/sipity/conversions/convert_to_polymorphic_type_spec.rb
spec/repositories/sipity/queries/permission_queries_spec.rb

As I'm making assumptions about deriving an object's polymorphic type
from an ActiveRecord::Base object, I want to encode that logic and
meaning. It provides a convenience method to explain to newcomers the
information that is part of Rails's conventions/idioms.
As the second commit, I'm replacing the opaque `class.base_class` with a more
explicit method call, stating what is happening.

Adding conversion method for entity type

---

app/exceptions/sipity/exceptions.rb
app/services/sipity/services/notifier.rb

I want the exception that is raised to have an indicator of what the
container and message was.

Adjusting NotificationNotFoundError type

---

app/models/sipity/models/sip.rb
spec/models/sipity/models/sip_spec.rb

At this point, the system is being built with ETDs in mind. However,
other work types (i.e. Senior Thesis) may very well enter into the
application. I want to begin laying the ground work for that.
At present, I'm envisioning an enum, as that is the quickest thing to
implement. If Sipity is to become an application for everyone, its
going to get more complicated as we proceed. But that is a problem for
tomorrow.

Adding work_type to Sip

---

app/models/sipity/models/sip.rb
db/migrate/20150108164454_add_work_type_to_sip.rb
db/schema.rb
spec/models/sipity/models/sip_spec.rb

Following on sipity@e0e1a8a, I want to make sure that we are capturing
work_type and persisting it. The current implementation is naive in
that it assumes only one work type. However, we will certainly be
adding additional ones over the coming weeks.

Persisting Sip#work_type

---

app/exceptions/sipity/exceptions.rb
app/policies/sipity/policies.rb
app/policies/sipity/policies/base_policy.rb
app/policies/sipity/policies/enrich_sip_by_form_submission_policy.rb
app/policies/sipity/policies/sip_policy.rb
app/services/sipity/services/authorization_layer.rb
app/state_machines/sipity/state_machines/etd_student_submission.rb
spec/policies/sipity/policies/base_policy_spec.rb
spec/policies/sipity/policies_spec.rb
spec/runners/sipity/runners/base_runner_spec.rb
spec/services/sipity/services/authorization_layer_spec.rb
spec/state_machines/sipity/state_machines/etd_student_submission_spec.rb

As I'm working on the `./artifacts/permission_model.md` I added
glossary items for PolicyQuestion and Action; They were aliases. So I
am instead prefering to use the more explicit :action_to_authorize.

Renaming policy_question to action_to_authorize

---

app/policies/sipity/policies/sip_policy.rb
app/repositories/sipity/commands/notification_commands.rb
app/repositories/sipity/commands/permission_commands.rb
app/repositories/sipity/queries/permission_queries.rb
app/state_machines/sipity/state_machines/etd_student_submission.rb
db/migrate/20141204154424_create_sipity_permissions.rb
db/migrate/20150108151201_create_sipity_models_actor_for_permission_assignments.rb
db/schema.rb
spec/models/sipity/models/permission_spec.rb
spec/policies/sipity/policies/sip_policy_spec.rb
spec/repositories/sipity/commands/notification_commands_spec.rb
spec/repositories/sipity/commands/permission_commands_spec.rb
spec/repositories/sipity/commands/sip_commands_spec.rb
spec/repositories/sipity/queries/permission_queries_spec.rb
spec/state_machines/sipity/state_machines/etd_student_submission_spec.rb

The word "role" comes with so much baggage. In conversations, it can
easily be mixed with the idea of a group (i.e. Catalogers can be
easily perceived as a Group and a Role).
This is unlikely to be the final name, but it creates a new word that
allows for easier future changes.
In an effort to better reflect the intention of the parameter and
methods, I'm renaming a few of them as well.
NOTE: This is a major change, you will need to drop your development
and test database and load the new schema:
```console
rake db:drop db:create db:schema:load
```

Renaming role to acting_as

---

app/jobs/sipity/jobs.rb

My goal with this move is to improve the legibility of the module and
its related methods. My question to the reviewer is "Does this change
make the module easier to understand?"
As per a conversation with @rbalekai:
> it will probably help more in PRs
> when new methods are added to the modules
> so that we dont have to open the whole file to see whats doing on

Moving module_function declaration to method def

---

app/policies/sipity/policies.rb
app/repositories/sipity/commands/collaborator_commands.rb
app/repositories/sipity/commands/permission_commands.rb
app/repositories/sipity/queries/permission_queries.rb
spec/support/sipity/factories.rb

Instead of the important module_function declaration at the top of the
module, I want close association with the defined method. This will
help with pull requests legibility.
See sipity@dacfcb4108b6afd98562249fed2a4abe1e5aaa1a

Reworking low hanging module_function defs

---

app/services/sipity/services/doi_creation_request_metadata_gatherer.rb

Is the before commit more expressive or less? Consider the visual
chatter of the method.
Another option to consider is treating the method analogous to the
Array() method (see below).
```ruby
ConvertToYear(publication_date).to_s
```

Switching to module inclusion for conversion

---

app/models/sipity/models/attachment.rb
app/models/sipity/models/sip.rb
db/migrate/20150112142919_create_sipity_models_attachments.rb
db/schema.rb
spec/models/sipity/models/attachment_spec.rb
spec/models/sipity/models/sip_spec.rb

This migration is ported over from Hydramata::Works. We will need to
associate attachments with a given sip. These attachments are their
own entity (hence the PID).

Adding Sipity::Models::Attachment

---

app/controllers/sipity/controllers/sips_controller.rb
app/runners/sipity/runners/sip_runners.rb
spec/controllers/sipity/controllers/sips_controller_spec.rb
spec/runners/sipity/runners/sip_runners_spec.rb

This feature is intended to provide consumers of Sipity to provide
direct links that allow form elements to be pre-populated.
This is something that is necessary for the ETD system, as patrons
preparing their ETD for deposit need not concern themselves with
choosing which work type they are submitting.

Allow passed parameters to populate new Sip form

---

app/models/sipity/models/access_right.rb
artifacts/sipity-erd.dot
db/migrate/20150113145636_create_sipity_models_access_rights.rb
db/schema.rb
spec/models/sipity/models/access_right_spec.rb

I opted to create a separate model as both a Sip and an
associated Attachment could have different access rights. I also went
the route of implementing a date range to reflect that as we deal with
Embargo's and Lease's the data gets convoluted as we attempt to
reflect two concepts (rights and dates) in one user input.

Create AccessRight model

---

app/models/sipity/models/sip.rb
app/models/sipity/models/transient_answer.rb
artifacts/sipity-erd.dot
db/migrate/20150113155503_create_sipity_models_transient_answers.rb
db/schema.rb
spec/models/sipity/models/transient_answer_spec.rb

There are some answers that we ask our patrons to complete that are
prompts for additional thought or consideration. This model is the
persistence of those answers, and is to be used to continue prompting
for more permanent information.
Consider the question about Access Rights. There are three somewhat
simple answers: Open, Restricted, and Private. However with the
concept of Embargos and Leases, the actual answer can require a whole
lot more prompting; namely when does one access right start and the
other end?

Adding Transient Answer model

---

app/mailers/sipity/mailers/email_notifier.rb
app/state_machines/sipity/state_machines/etd_student_submission.rb
spec/mailers/sipity/mailers/email_notifier_spec.rb
spec/state_machines/sipity/state_machines/etd_student_submission_spec.rb

The notification name, while correct, is made more correct by
renaming it to something that better reflects the state of the entity.

Renaming email notification name

---

app/models/sipity/models/transient_answer.rb
app/repositories/sipity/commands/transient_answer_commands.rb
app/repositories/sipity/commands/work_commands.rb
spec/repositories/sipity/commands/transient_answer_commands_spec.rb

In three of the four base cases, Sipity can write more "permanent"
information as it relates to the entity. This is also a question that
I want no more than one transient answer.

Handling access rights transient answer

---

app/jobs/sipity/jobs.rb
app/policies/sipity/policies.rb
app/repositories/sipity/commands/permission_commands.rb
app/repositories/sipity/commands/transient_answer_commands.rb
app/repositories/sipity/queries/permission_queries.rb
spec/support/sipity/factories.rb

I am running into a case where the Ruby beautifier (and to some extent
style guide) are not liking the module_function with method def. What
happens is the auto-beautify is getting very confused. I use the auto-
beautify to make sure spacing is "correct" and there is no trailing
white-space.

Reworking module_function declaration

---

app/decorators/sipity/decorators/entity_enrichment_action.rb
app/decorators/sipity/decorators/work_decorator.rb
app/views/sipity/controllers/works/show.html.erb
config/locales/en.yml
spec/decorators/sipity/decorators/entity_enrichment_action_spec.rb
spec/decorators/sipity/decorators/work_decorator_spec.rb

EntityEnrichmentActions are going to vary by:
* User - some users may not need to or be able to see a certain option
a grad may not be given the opportunity to add all kinds of
metadata to their deposit, that may be reserved for an approving
librarian or metadata specialist)
* State - based on an object's state, additional enrichments may not
be available; Once an ETD has been approved for review we may choose
to disallow one or more forms, opting instead to make the "kitchen
sink" enrichment option available.
* Entity Type - the enrichment options for an ETD vs. an Image vs.
some other work type will vary
An important thing as we continue developing this application is to
make sure that we have named concepts. In naming things we can grow
our understanding as a team. It also draws …

Rendering EntityEnrichmentAction in show view

---

app/forms/sipity/forms/create_work_form.rb
app/repositories/sipity/commands.rb
app/repositories/sipity/commands/work_commands.rb
app/runners/sipity/runners/work_runners.rb
spec/forms/sipity/forms/create_work_form_spec.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/repositories/sipity/queries/work_queries_spec.rb
spec/runners/sipity/runners/work_runners_spec.rb

* Polymorphism related to forms - That is to say each form has a
reasonable idea of what it needs to do; so do that. This aligns
better with the Reform and ActiveForm behaviors
* Begin removing repository command module_functions - Given that many
of the command behaviors were both a module_function and an instance
method, it implies a certain complexity and leakyness in the
abstraction.
* Removes several methods from the command modules
* Pushes the relevant form code closer to the object in question.
See Sipity@e4dfa9a7d7ed6dc0ad81858095f9145786aa7bb5 for additional
commentary regarding why this change

Extracting #submit method to form

---

app/decorators/sipity/decorators/entity_enrichment_action.rb
app/decorators/sipity/decorators/work_decorator.rb
app/views/sipity/controllers/work_descriptions/new.html.erb
app/views/sipity/controllers/works/show.html.erb
config/routes.rb
spec/decorators/sipity/decorators/entity_enrichment_action_spec.rb
spec/features/sipity/create_minimum_viable_work_spec.rb
spec/support/site_prism_support.rb

Building on DLTP-346 and preparing for DLTP-347, I'm looking to reduce
the need for multiple controllers based on enrichment.
This current step is moving the routing to a less resource-based route
and more of a task-based route.
From:
```ruby
resources :works do
resource :work_description
end
```
To:
```ruby
get(
'works/:work_id/describe',
to: 'work_descriptions#new', as: 'describe_work'
)
post 'works/:work_id/describe', to: 'work_descriptions#create'
```
My eventual goal for describe and attach are to leverage a shared
route as follows:
```ruby
get(
'works/:work_id/:enrichment_type',
to: 'work_descriptions#new', as: 'enrich_work'
)
post 'works/:work_id/:enrichment_type', to: 'work_enrichments#update'
```
Note that the action names change from #new/#update to #edit/#create.
This is …

Preparing for next enrichment

---

app/decorators/sipity/decorators/entity_enrichment_action.rb
app/decorators/sipity/decorators/todo_list.rb
app/decorators/sipity/decorators/work_decorator.rb
app/views/sipity/controllers/works/show.html.erb
spec/decorators/sipity/decorators/entity_enrichment_action_spec.rb
spec/decorators/sipity/decorators/todo_list_spec.rb
spec/decorators/sipity/decorators/work_decorator_spec.rb
spec/support/site_prism_support.rb

I want to create a common interface for rendering a work's todo items.
This is not the final state of the rendering but it is enough to allow
work to continue on the todo item.
I want a way to dynamically generate the TODO list for rendering on
the work page. Right now I may be mixing the enrichment and todo items
before they should be mixed. However, the goal is to push up a
rudimentary listing option for dynamic rendering.
As per a conversation with Dan, as we move towards a TODO based page
rendering, I want to expose the status for view rendering.

Adding todo list

---

app/views/sipity/controllers/works/show.html.erb
spec/support/site_prism_support.rb

As part of an experiment we are attempting to reduce the collision of
concerns related to CSS, Javascript, and automated testing.
Dan will be working to articulate the markup guidelines; At present
we are looking to reserve dom classes for CSS and JS interaction.
Testing is a somewhat different concern. The hope is that by spending
time marking up via Schema.org, when someone sees that markup they
will consider "What does this mean?" and be less prone to
modification.
REVIEW: This is an experimental idea; We are using the Schema.org
structure to drive our automated testing. This should be viewed as
experimental and will be part of an ongoing conversation amongst the
developers.

Marking up our action via Schema.org

---

.hound.yml
Rakefile
app/repositories/sipity/commands.rb
lib/tasks/sipity.rake
spec/support/sipity/command_repository_interface.rb

This is an experimental proposal, but one that I want to start kicking
around.
The intent is to create an object that has the same method signature
of existing repository methods; This way we can leverage a mock
repository that conveys the corresponding method signatures.
The implementation is a bit naive as it will grab any and all public
and private methods. Something like Github: seattlerb/sexp_processor.

Creating a sipity:rebuild_interfaces task

---

app/controllers/sipity/controllers/work_enrichments_controller.rb
app/forms/sipity/forms/describe_work_form.rb
app/models/sipity/models/additional_attribute.rb
app/runners/sipity/runners/work_enrichment_runners.rb
app/views/sipity/controllers/work_enrichments/describe.html.erb
config/initializers/simple_form.rb
spec/controllers/sipity/controllers/work_enrichments_controller_spec.rb
spec/features/sipity/create_minimum_viable_work_spec.rb
spec/forms/sipity/forms/describe_work_form_spec.rb
spec/runners/sipity/runners/work_enrichment_runners_spec.rb
spec/support/site_prism_support.rb

This is an initial conjecture. I'm not certain what attributes we will
attempt to capture but I'm laying the initial groundwork.
Also, a minor tweak related to the enrichment_type; a work does not
have an enrichment type, but I can instead use the parameter to derive
that information.
I am exposing a singular end-point for updating an enrichment. Each of
the envisioned enrichments will behave in a similar manner (hence a
unified controller aciton).
Moving towards naming things, this exposes a method consistent with
the behavior of the Schema.org/Action update.
See sipity@fc4a444b114e559fad39bd6d0df68bd8b5f989c5
This is the generalized behavior. I hope to push most enrichment forms
through this controller. Ultimately it is a decision of the router to
handle this behavior.

Adding ability to update an enrichment

---

app/forms/sipity/forms/create_work_form.rb
app/models/sipity/models/todo_item_state.rb
app/repositories/sipity/commands.rb
app/repositories/sipity/commands/todo_list_commands.rb
db/migrate/20150122181425_create_sipity_models_todo_item_states.rb
db/schema.rb
spec/models/sipity/models/todo_item_state_spec.rb
spec/repositories/sipity/commands/todo_list_commands_spec.rb
spec/support/sipity/command_repository_interface.rb

Responsible for persisting the state of a todo list item for a given
entity and its processing state.
Given that there is a state related to todo items, I need to have a
means of querying that state to present the todo list to a user. The
most obvious method is to track what to do items are associated with
the work at the given state.
I'm working my way around the todo list/enrichment design, attempting
to resolve how this information will be tracked. Its a multi-
dimensional problem: WorkType, State, Items maps to Work, User, State,
Items.
I want to populate the todo list for a new work; This list is not yet
retrieved, but is somewhat easy to capture.

Adding work type todo

---

app/views/sipity/controllers/work_event_triggers/new.html.erb
app/views/sipity/controllers/works/show.html.erb
spec/support/site_prism_support.rb

Given that an action can have entryPoints and an entryPoint can have
possibleActions, which one is the parent container is somewhat
arbitrary.
However, given that a Thing > CreativeWork can have a potentialAction
it makes sense that the Action would contain the entryPoint. In this
way I can have the nested concept, and push the actions into the
CreativeWork container (as they are actions to take on that work).

Inverting the potentialAction and entryPoint relation

---

app/forms/sipity/forms/work_event_trigger_form.rb
app/policies/sipity/policies/work_event_trigger_policy.rb
app/repositories/sipity/queries/permission_queries.rb
app/state_machines/sipity/state_machines.rb
app/state_machines/sipity/state_machines/etd_state_machine.rb
spec/features/sipity/trigger_work_state_change_spec.rb
spec/forms/sipity/forms/work_event_trigger_form_spec.rb
spec/policies/sipity/policies/work_event_trigger_policy_spec.rb
spec/repositories/sipity/queries/permission_queries_spec.rb
spec/state_machines/sipity/state_machines/etd_state_machine_spec.rb
spec/state_machines/sipity/state_machines_spec.rb

There are quite a few actors/collaborators in this sequence; I'm going
to be visiting those and attempting to stitch together their
collaboration.
I want to access this information.
Leveraging the finder, I'm getting the state diagram for a given work
type.
I need to know specifically if the given :user can act as the given
:acting_as on the given :entity
Stepping through the various scenarios on policy enforcement.
The previous policy is one that was more liberal in what could be
done. The WorkEventTriggerPolicy makes sure all critera for events
are met.

Work event trigger policy

---

.hound.yml
app/exceptions/sipity/exceptions.rb
app/policies/sipity/policies/work_event_trigger_policy.rb
app/state_machines/sipity/state_machines/etd_state_machine.rb
app/state_machines/sipity/state_machines/state_diagram.rb
spec/exceptions/sipity/exceptions_spec.rb
spec/forms/sipity/forms/work_event_trigger_form_spec.rb
spec/policies/sipity/policies/work_event_trigger_policy_spec.rb
spec/state_machines/sipity/state_machines/etd_state_machine_spec.rb
spec/state_machines/sipity/state_machines/state_diagram_spec.rb
spec/state_machines/sipity/state_machines_spec.rb

@436d18ce95a6ee57175ad4ae287ff535f4c51986
Encapsulate the state diagram and potential "acting_as" values.
@3b70051b574ebb2b64eff36fc84ae7510b340b43
Removing over usage of nested fetch imperatives; Prefer an object to
answer what was requested.
@06e736f601601f4d698d90d93132446483d02fe5

Adding state diagram object

---

CONTRIBUTING.md
scripts/build-multi-commit-message

The attached script will generate a somewhat markdown compatable
string that can be used as the message of the pull request. This is
useful if your pull request has multiple commits.
[skip ci]

Adding script and note concerning multi-commits

---

app/state_machines/sipity/state_machines/state_diagram.rb
spec/state_machines/sipity/state_machines/state_diagram_spec.rb

So I know who all the "acting_as" are for a given state and events
that could be run.

Adding #available_event_triggers

---

Gemfile
Gemfile.lock

It had started throwing an error for me:
`uninitialized constant Guard::UI::ERROR_TERMINAL_NOTIFIER_ONLY_OSX10`

Bumping version of terminal-notifier-guard

---

app/models/sipity/models/permission.rb
app/repositories/sipity/commands/permission_commands.rb
app/repositories/sipity/commands/work_commands.rb
spec/repositories/sipity/commands/work_commands_spec.rb

As a grad student when I assign a NetID for an advisor that requires
signoff
Then I want to associate the work with my advisor's NetID
So that my advisor can review the document
Closes DLTP-368

Associating an advisor with grad school members

---

app/controllers/sipity/controllers/dashboards_controller.rb
app/repositories/sipity/queries/permission_queries.rb
app/repositories/sipity/queries/work_queries.rb
app/runners/sipity/runners/dashboard_runners.rb
app/state_machines/sipity/state_machines/state_diagram.rb
app/views/sipity/controllers/dashboards/index.html.erb
config/routes.rb
spec/controllers/sipity/controllers/dashboards_controller_spec.rb
spec/features/sipity/enriching_a_work_spec.rb
spec/repositories/sipity/queries/permission_queries_spec.rb
spec/repositories/sipity/queries/work_queries_spec.rb
spec/runners/sipity/runners/dashboard_runners_spec.rb
spec/state_machines/sipity/state_machines/state_diagram_spec.rb

@493246c1e5c79c624392429faf2ddc1548323eb2
@3e856bcf01225167b49b10f3dc4670dc1f101b49
@e127a3d9b2b1ddaabddea111a4cc7cd0e87940bd
I need to know this information for filtering purposes.
@28f7d8221a0340c4c68cf297d0b7f45d2bf545f6
I want to allow for the processing state to be used as a filter on the
dashboard.
@dea2a7fd10bc57a2f77a0dfd99893a68d6046e3b
@5c00f0757ec1710663732135f3c8e8e4aaba13ea
@01595debca9adf99098001b6dcc7cfddef086a2a
@9e1a50bd886af771933a75c514dd3dbab1198c2a

DLTP 370 dashboard page

---

app/models/sipity/models/processing/strategy.rb
app/models/sipity/models/work_type.rb
db/migrate/20150205171226_create_sipity_models_work_types.rb
db/migrate/20150205172137_adding_work_type_to_processing_strategy.rb
db/schema.rb
db/seeds.rb
spec/models/sipity/models/processing/strategy_spec.rb
spec/models/sipity/models/work_type_spec.rb
spec/repositories/sipity/queries/processing_queries_spec.rb

@63209daa755d395252d02e6bc2f9c59f1350aa6f
Given that I may need to drive additional information based on the
WorkType, I want a place that I can begin to describe that
information.
Yes, I could continue to use the magic name, and in some cases I will,
but if I want an association to a ProcessingStrategy, I believe I
should perform my due diligence and craft a proper relationship.
@9b6b2468937d018b335430b6644b089ee364f820
Switching from a DB-less model to one backed by ActiveRecord::Base.
This also results in changes to the seeds.
@aec418aa67f4fe434b5a104d2adb9da2a66d9f04
Mirroring the behavior of the Processing::Actor and Processing::Entity
I want to do likewise for the WorkType.
@2647c2d76263c4d463efdb4bd3a4ba2940d10160
By creating the relationship, I'm able to work towards creating a …

Adding work type to database

---

app/forms/sipity/forms/create_work_form.rb
app/models/sipity/models/processing/strategy.rb
app/models/sipity/models/work_type.rb
app/repositories/sipity/commands/work_commands.rb
db/migrate/20150205183848_amending_processing_entity_indices.rb
db/schema.rb
db/seeds.rb
spec/forms/sipity/forms/create_work_form_spec.rb
spec/models/sipity/models/processing/entity_spec.rb
spec/models/sipity/models/processing/strategy_spec.rb
spec/models/sipity/models/processing/strategy_state_spec.rb
spec/models/sipity/models/work_type_spec.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/support/sipity/command_repository_interface.rb

@2b7901f428f817eda65b8d5f8b55ae58b14b51bb
I want a method to handle both the work creation and its corresponding
processing proxy object.
@bfa6577f81eaf79609d3210e9f210cccb8a09a1d
Because I was wanting to see what the database columns were, I figured
I may as well add tests to verify.
@e6c04d70769bdac72f198357153cf8ac42953a59
@3018d4244007622ff36caa10826e3a33265385d6
@459ad8677349d9e40e8d3df7499329ef1a0fd790
Because I was wanting to see what the database columns were, I figured
I may as well add tests to verify.
@17dbe91c07ca7088b606805847fb9248f61166c3
This is hard-coding, but it helps bootstrap the behavior as expected.
I'd prefer to have a convention related to how a processing strategy
"gets started".
@84d82075b0c9168f2488d16434ce20468777f403
Again, this is hard-coding expectaions, …

Adding create processing entity when work is created

---

spec/forms/sipity/forms/work_enrichments/collaborator_form_spec.rb
spec/models/sipity/models/work_type_spec.rb
spec/policies/sipity/policies/work_event_trigger_policy_spec.rb
spec/services/sipity/services/grant_processing_permission_spec.rb
spec/services/sipity/services/update_entity_processing_state_spec.rb

In an ongoing effort to make sure that the feature tests are
"disposable", I want to ensure that code coverage is 100% without
features.
This is done by running:
`$ rake spec:coverage:without_features`
There were a few missing cases, but they have been shored up.

Adding specs to ensure code coverage w/o features

---

app/forms/sipity/forms/work_enrichments/collaborator_form.rb
app/repositories/sipity/queries/collaborator_queries.rb
spec/forms/sipity/forms/work_enrichments/collaborator_form_spec.rb
spec/repositories/sipity/queries/collaborator_queries_spec.rb

I encountered an odd interaction that is a result of @3d612b50.
Building the form went from:
```ruby
work = repository.find_work(work_id)
form = repository.build_enrichment_form(work: work, enrichment_type: enrichment_type)
```
to
```ruby
work = repository.find_work(work_id)
decorated_work = Decorators::WorkDecorator.decorate(work)
form = repository.build_enrichment_form(work: decorated_work, enrichment_type: enrichment_type)
```
It appears the intent of adding the decoration is to get the following:
```ruby
def with_action_pane(name, css_class = '', &block)
h.render(layout: 'sipity/form_action_pane', locals: { name: name, css_class: css_class, object: self }, &block)
end
```
https://github.com/ndlib/sipity/blob/3d612b50/app/decorators/sipity/decorators/work_decorator.rb#L17-L20
This …

Replacing object query with repository query

---

app/repositories/sipity/commands/work_commands.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/support/sipity/command_repository_interface.rb

@banurekha noticed this behavior. In the previous implementation
I was hoping the named :pid_minter parameter, if nil would set the
named parameter to the module's `pid_minter` method. However it was
setting the named parameter's value to itself, thus
`attach_file_to(work: work, file: file, user: user)` would result in
the pid_minter parameter being nil.
This clarifies the behavior, and while I would prefer a pid_minter
method, I will settle for default_pid_minter.
Good catch @banurekha
Also, appeasing Rubocop's identification that the user parameter was
not needed. I know we need it, but for now, I'll settle one what we
have.

Renaming pid_minter to default_pid_minter

---

app/forms/sipity/forms/create_work_form.rb
spec/forms/sipity/forms/create_work_form_spec.rb

The HTML form that was capturing this information no longer has a
publication date associated with it. So I'm removing the validation.
If you give us one, we'll capture it.

Removing validation as input is not user available

---

app/repositories/sipity/queries/enrichment_queries.rb
spec/fixtures/seeds/trigger_work_state_change.rb
spec/models/sipity/models/processing/strategy_action_prerequisite_spec.rb
spec/repositories/sipity/queries/enrichment_queries_spec.rb
spec/repositories/sipity/query_repository_spec.rb

@a38da10e93033e1b995b4c434ed2ec5de72a3d56
I was looking these up so I figure I should write a test for them.
@648d746232bfe7a2ee7fe239df346c132796d0a4
@96885eed115c3cdea6453c6412665b030b9e25d2
Note: This breaks an underlying test about method duplication.
@cf9dfacfd274eb2f6f733db3c860c73a97706e31
This should be re-enabled once the long-term solution for processing
queries has been implemented.
@c3b5e583fe94eb44f3e724221b19f0628a878053

Leverage action queries

---

app/repositories/sipity/queries/processing_queries.rb
spec/repositories/sipity/queries/processing_queries_spec.rb

@dfdb03056d67eec4753c898c043d87334c96676f
Spending a bit of time solving the generalized problem.
@dd914de843a8a1391473afd0f775c780b9e006d7
> An ActiveRecord::Relation scope that meets the following criteria:
>
> * Processing Entities with the given processing strategy
> * Processing Entities that the user has one or more roles associated
>   with, either:
>   * Directly via the StrategyResponsibility (and Processing::Actor)
>   * Indirectly via the EntitySpecificResponsibility (and
>     Processing::Actor)
>
> @param user [User]
> @param strategy [Sipity::Models::Processing::Strategy]
> @param roles [Array<Sipity::Models::Role>]
>
> @return ActiveRecord::Relation<Models::Processing::Entity>

Working on processing queries

---

app/views/sipity/controllers/work_enrichments/collaborators.html.erb
app/views/sipity/controllers/work_enrichments/describe.html.erb
app/views/sipity/controllers/work_event_triggers/new.html.erb
app/views/sipity/controllers/works/show.html.erb
spec/features/sipity/enriching_a_work_spec.rb
spec/features/sipity/trigger_work_state_change_spec.rb
spec/features/visitors/about_page_spec.rb
spec/features/visitors/home_page_spec.rb
spec/features/visitors/navigation_spec.rb
spec/support/database_cleaner.rb
spec/support/site_prism_support.rb

As I was working with capybara-accessible, I encountered the problem
where the HTML document was being sent off to Google's accessibility
validation service and would come back altered.
The service returned an HTML document that converted the META content
"todo>required" to "todo&gt;required". As I want to be able to run
these accessibility tests, this is a required change.
https://github.com/Casecommons/capybara-accessible

Replacing > with / for Schema.org named actions

---

.hound.yml
Gemfile
Gemfile.lock
Rakefile
spec/support/capybara.rb
spec/support/site_prism_support.rb

In an effort to ensure accessibility, I'm looking to automate that
behavior using the capybara-accessible gem. Out of the box, these
tests are slower (as they are using Poltergeist to interact via a
headless browser instead of with an HTML page).
I needed to make changes to allow for hidden elements to be found.
I also wanted an option to run choose whether to run with or without
accessibility.

Adding ability to conditionally run accessibility

---

app/conversions/sipity/conversions/convert_to_processing_action_name.rb
app/exceptions/sipity/exceptions.rb
app/models/sipity/models/processing/strategy_action.rb
app/policies/sipity/policies/processing/work_processing_policy.rb
app/repositories/sipity/queries/enrichment_queries.rb
app/repositories/sipity/queries/permission_queries.rb
app/repositories/sipity/queries/processing_queries.rb
app/repositories/sipity/query_repository.rb
spec/conversions/sipity/conversions/convert_to_processing_action_name_spec.rb
spec/models/sipity/models/processing/strategy_action_spec.rb
spec/policies/sipity/policies/processing/work_processing_policy_spec.rb
spec/repositories/sipity/queries/processing_queries_spec.rb
spec/repositories/sipity/query_repository_spec.rb

@47436b36252f17d69a719d73d195921c582968a3
Moving methods around for organizational purposes. Restoring the test
to verify that repositories do not have colliding method definitions.
@3c6f46d8aa241adb6104a82e9034c15555f789d6
Given that I am crossing boundaries between processing and the
controllers, and that I have cases of :update? when the corresponding
action name is 'edit', I want to have a codified location that
explains this mapping.
@dd45f6d49c99b92dd2884695ae39de03bfa4a615
I want the data to be written in consistent measures so that
associated controller actions pairs (i.e. new/create and edit/update)
are treated similarly.
@178ab9e75ff89e79577319618de36fea250c371c
This query leverages underlying behavior but tidies it up to be a
boolean response. …

Refactoring policy questions

---

.hound.yml
app/repositories/sipity/queries/collaborator_queries.rb
spec/repositories/sipity/queries/collaborator_queries_spec.rb

@e7fcc22f12f3999ce81d612d1437920c5fd6c290
Given that we need to know who requires signoff, this is a
foundational query. By itself it may not have a lot of meaning, but as
I move towards the form regarding advisor signoff, I will need to know
who are all the collaborators for which I will require signoff.
@9f8ac0752a0c5aed7b33bbbab648f04d5173e53e
I'm not feeling up to converting a collaborator into an actor (though
perhaps that would make more sense). So this is my way of saying only
collaborators that are users in the system.
@f3aeaf61cdb78fab41ace9a6546713dba65cdd6a
Given that the query subsystem is making judicious use of the Arel
syntax, I'm easing the cyclomatic complexity problem by saying "lets
not worry about that for the queries".

Querying Collaborators Requiring Signoff

---

Gemfile
Gemfile.lock
app/decorators/sipity/decorators/processing/state_advancing_action_decorator.rb
app/repositories/sipity/queries/processing_queries.rb
spec/fixtures/seeds/scope_strategy_actions_with_incomplete_prerequisites.rb
spec/repositories/sipity/queries/processing_queries_spec.rb

@ff717ba7d7da7b3f623dbbba1c2a4fd269b55df4
For clarity and less chattiness, making adjustments to the test.
@1812b9224d88ec1897c3e2d2aa953facfe8b7d45
This allows us to dump the data into seeds.
@d394f54560a2acb3a700fed07dfd2ac16411324a
This is, I hope, a stop gap for the long term data stewardship.
@c32bf57bb2682e0bfe56e9ff3569ee13423d38ca
This addresses the issue in which a user has completed one of the
prerequisite actions for a guarded action, but not all of them.
Prior to the fix, if the user completed one prerequisite action then
a guarded action would be available. After this fix a guarded action
is only available if all of the actions have been completed.
@2d6df695bc12b6ffb01b17849985f7d5d76f684d

Fixing prereq action fulfillment answer

---

app/conversions/sipity/conversions/convert_to_processing_action.rb
app/conversions/sipity/conversions/convert_to_processing_strategy_id.rb
app/exceptions/sipity/exceptions.rb
app/forms/sipity/forms/etd/advisor_signoff_form.rb
app/forms/sipity/forms/etd/submit_for_review_form.rb
app/forms/sipity/forms/processing_action_form.rb
app/repositories/sipity/queries/collaborator_queries.rb
app/repositories/sipity/queries/processing_queries.rb
app/services/sipity/services/advisor_signs_off.rb
app/services/sipity/services/register_action_taken_on_entity.rb
db/migrate/20150201002854_create_sipity_models_processing_entities.rb
spec/conversions/sipity/conversions/convert_to_processing_action_spec.rb
spec/conversions/sipity/conversions/convert_to_processing_strategy_id_spec.rb
spec/forms/sipity/forms/etd/advisor_signoff_form_spec.rb
spec/forms/sipity/forms/etd/submit_for_review_form_spec.rb
spec/repositories/sipity/queries/collaborator_queries_spec.rb
spec/repositories/sipity/queries/processing_queries_spec.rb
spec/services/sipity/services/advisor_signs_off_spec.rb
spec/services/sipity/services/register_action_taken_on_entity_spec.rb

@39371253ddf88aa8a90bd44e61771a9ce9b06edf
There are some conditionals in this behavior. I want to make sure that
I'm isolating those decisions as the advisor signs off form is already
overworked.
One concern, however, is that I'm driving a querying decision off of
a thing that happens in an unrelated action; The
ProcessingActionForm's save method is registering that the action was
taken. This is buried in the implementation details, and has already
happened.
@e18142dc75ebf450ff1c7c4d92cfc467330a5345
> An ActiveRecord::Relation scope that meets the following criteria:
>
> * Any user that has taken the action (or someone has taken it on
>   their behalf)
> * Any user that is part of a group that has taken the action (you
>   know, because maybe we'll allow groups to take the action)
>
> …

Adding advisor signoff form

---

app/forms/sipity/forms/work_enrichments/defense_date_form.rb
app/forms/sipity/forms/work_enrichments/describe_form.rb
app/views/sipity/controllers/work_enrichments/defense_date.html.erb
config/routes.rb
db/seeds.rb
spec/forms/sipity/forms/work_enrichments/defense_date_form_spec.rb
spec/forms/sipity/forms/work_enrichments/describe_form_spec.rb
spec/routing/work_flow_routing_spec.rb

@b02f88404657d176b3f24eba26c3385ee3958729
I don't want the abstract_from_work to be an exposed public method. It
is something that happens on initialization and should not be called
at a future point.
Also clarifying how the values are initialized if none are passed.
@11993a4939d46c58f31e511b53180249ab2a05a9
Responsible for capturing information related to the defense date.
@4b8460f56cd9feb094d2afc3d6fe728b865f27f8

Adding thesis defense date form

---

app/models/sipity/models/work.rb
app/models/sipity/models/work_type.rb
app/state_machines/sipity/state_machines/doctoral_dissertation_state_machine.rb
app/views/sipity/controllers/dashboards/index.html.erb
config/locales/simple_form.en.yml
db/seeds.rb
spec/decorators/sipity/decorators/processing_actions_spec.rb
spec/features/sipity/enriching_a_work_spec.rb
spec/features/sipity/trigger_work_state_change_spec.rb
spec/fixtures/seeds/scope_processing_entities_for_the_user_and_proxy_for_type.rb
spec/fixtures/seeds/scope_strategy_actions_with_incomplete_prerequisites.rb
spec/fixtures/seeds/trigger_work_state_change.rb
spec/models/sipity/models/work_spec.rb
spec/models/sipity/models/work_type_spec.rb
spec/repositories/sipity/commands/todo_list_commands_spec.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/repositories/sipity/queries/enrichment_queries_spec.rb
spec/repositories/sipity/queries/permission_queries_spec.rb
spec/repositories/sipity/queries/processing_queries_spec.rb
spec/state_machines/sipity/state_machines/doctoral_dissertation_state_machine_spec.rb
spec/state_machines/sipity/state_machines_spec.rb

@9d8e8856785a492c0d76ef1d26e1d5e96d2fc7df
Given that ETD represented the Doctoral Dissertation and Master's
Thesis concept, and the DD and MT vary in required information that we
collect; Then we need to separate their definitions.
@3c395542e5387c9713400d9d5eb0d254dc73cc74
The difference between MasterThesis and DoctoralDissertation is that
the DefenseDate is pre-requisite for submitting a DoctoralDissertation
for review; Whereas it is optional for a MasterThesis.

Renaming ETD to Doctoral Dissertation

---

app/repositories/sipity/queries/processing_queries.rb
spec/features/sipity/trigger_work_state_change_spec.rb
spec/fixtures/seeds/rendering_correct_actions_based_on_user_entity_state.rb
spec/fixtures/seeds/trigger_work_state_change.rb
spec/repositories/sipity/queries/processing_queries_spec.rb

@c5988b1238ee139954d35271339ac5ec5bc59fcf
Addresses a bug found on the punch list:
> Optional todo items are still available for completion while a work
> is under advisor review.
@7b6358093c870c35a6a91ce5a88d480f375b9d03
Addresses the following:
> Optional todo items are still available for completion while a work
> is under advisor review.
This was occuring because in the originating state, the optional
actions were visible to the creating user. Once the state advanced,
the available action query was not accounting for the state of the
entity.

Updating processing query

---

app/forms/sipity/forms/etd/advisor_requests_changes_form.rb
app/models/sipity/models/processing/comment.rb
app/repositories/sipity/commands/todo_list_commands.rb
db/migrate/20150225173436_create_sipity_models_processing_comments.rb
db/schema.rb
spec/forms/sipity/forms/etd/advisor_requests_changes_form_spec.rb
spec/models/sipity/models/processing/comment_spec.rb
spec/repositories/sipity/commands/todo_list_commands_spec.rb
spec/support/sipity/command_repository_interface.rb

@6b7ad367726feddf343d2cc6218ca1aa4d02187b
This highlights the behavior, however it calls attention to a few
interface changes that will need to occur.
@db91ae6125d6681e04538bf38504d4d44f997b57
> Responsible for capturing a :comment made by a given :actor on a
> given :entity at a given :originating_strategy_state as part of a
> given :originating_strategy_action.
@15431dcbc8dbc7662bc140abc2e837b3433fdded
> Responsible for capturing a :comment made by a given :commenter on a
> given :entity as part of a given :action.

Adding advisor requests changes

---

app/forms/sipity/forms/work_enrichments/defense_date_form.rb
spec/forms/sipity/forms/work_enrichments/defense_date_form_spec.rb

Handle the passing of invalid dates while still leaning on the
presence validation for the defense date.
This is again an interim solution.

Tidying up date parsing

---

app/controllers/sipity/controllers/work_event_triggers_controller.rb
app/forms/sipity/forms/etd/advisor_requests_changes_form.rb
app/forms/sipity/forms/processing_action_form.rb
app/mailers/sipity/mailers/email_notifier.rb
app/runners/sipity/runners/work_event_trigger_runners.rb
app/views/sipity/controllers/work_event_triggers/new.html.erb
spec/controllers/sipity/controllers/work_event_triggers_controller_spec.rb
spec/forms/sipity/forms/etd/advisor_requests_changes_form_spec.rb
spec/forms/sipity/forms/processing_action_form_spec.rb
spec/mailers/sipity/mailers/email_notifier_spec.rb

@c885b5f03084fad89dcb2e237fb476d5cfa56b5a
Prior to this change, the application was not accepting any additional
payload. However, this is something that is required.
@b70e81f4d72d7db2caec601a401c9caf5aa39f40
Now allowing attributes to be pased based on input
@78ccdf9495949fdd463c4fc483b20cb254fcbdb7
For the state changing event triggers, I want to be able to capture
additional information. The initial case is comments.
@b2976c19f912024ceb72d3407188bcba41732536
Adding the basis for sending an advisor_has_requested_changes email.

Adding ability to capture advisor comments

---

db/migrate/20150226134513_update_processing_entities_column_type.rb
db/schema.rb

In a moment of copy/paste blindness, I set a foreign key as a string.
While this works, it is less than optimal for queries/joins.

Adjusting column definition

---

db/seeds.rb

Instead of the more obtuse "approve_for_ingest" make the action name
more clear by stating intent of approval not speculation on what
happens next.

Renaming action for clarity

---

app/forms/sipity/forms/etd/approve_for_ingest_form.rb
app/forms/sipity/forms/etd/grad_school_signoff_form.rb
app/mailers/sipity/mailers/email_notifier.rb
app/state_machines/sipity/state_machines/doctoral_dissertation_state_machine.rb
artifacts/etd-submission-state-machine.dot
spec/fixtures/seeds/scope_strategy_actions_with_incomplete_prerequisites.rb
spec/forms/sipity/forms/etd/approve_for_ingest_form_spec.rb
spec/forms/sipity/forms/etd/grad_school_signoff_form_spec.rb
spec/mailers/sipity/mailers/email_notifier_spec.rb
spec/state_machines/sipity/state_machines/doctoral_dissertation_state_machine_spec.rb

@235eecb9dd6763afa45d4ffec75358c711f43383
This form captures the final approval by the Grad School
@fa9e44061be2a47aa59f1a6e75908e16af04e997
Building on @427e40973d3654a3f2a887588eae8a5658c1161e I want to
improve clarity of the actions intent, not foreshadow what comes next.
@b8ca08811df109758a638ce231c0b159519374aa

Adding approve for ingest form

---

app/decorators/sipity/decorators/dashboard_view.rb
app/policies/sipity/policies/work_policy.rb
app/repositories/sipity/queries/processing_queries.rb
app/repositories/sipity/queries/work_queries.rb
app/runners/sipity/runners/dashboard_runners.rb
app/views/sipity/controllers/dashboards/index.html.erb
db/migrate/20150226160732_adding_index_to_strategy_state_name.rb
db/schema.rb
spec/decorators/sipity/decorators/dashboard_view_spec.rb
spec/policies/sipity/policies/work_policy_spec.rb
spec/repositories/sipity/queries/processing_queries_spec.rb
spec/repositories/sipity/queries/work_queries_spec.rb
spec/runners/sipity/runners/dashboard_runners_spec.rb

For @danhorst 
@bf6147219a56e83464aad1c65c7e447419b40550
As the Dashboard gets more complicated, I want to make sure to
isolate those changes in a custom view object.
@ca2e392baf124366dd45d4e63aa96e1fdbde4289
@fbd22031e45453c9886c4e9a7f4afcbc6d01b28f
@44274b5f3e50a8eb2917fc63e3156ebb30a3b38f
By utilizing the dashboard view object, instead of the call out to
diagram states, I can begin to adjust the visible filter options to
what is visible for the current user.
That is a future exercise; For now I need to get the filter query
working.
@96f2016f6a30ad4398af056d052aae6b63f7d0d6
Prior to this change, the queries were filtering on the now non-
existent :processing_state column of the Sipity::Model::Work. This
change makes sure to filter by Processing State name.
Note: I'm opting for "name" …

Altering processing state dashboard query

---

app/forms/sipity/forms/work_enrichments/collaborator_form.rb
app/views/sipity/controllers/work_enrichments/collaborators.html.erb
config/initializers/simple_form.rb
config/locales/en.yml
spec/forms/sipity/forms/work_enrichments/collaborator_form_spec.rb

@11d2dcfb819a4af522500680b0ecfdd86ee37266
I want to make sure that at least one of the collaborators has been
marked as "requires review"
@908cce5a877be8d945981e5d4428be6a938d47ba
If there are multiple errors, I want them all to show up. This is how
we go about doing that.
@ec2ee35288e0c97ca7287d09011c04ec2d00b672
Given that we are rendering sentences, I don't want to have periods in
those sentences.
@fcfa8960e178a7c7c1d164cf35c9d224e638542f
Given that I may have an error on the base object, I want a means of
reporting that information. This is the quickest way to do it. We
could craft a helper method to deal with this as well.
Or our own FormBuilder

Enforcing at least one collaborator

---

app/decorators/sipity/decorators/processing/resourceful_action_decorator.rb
app/views/sipity/controllers/works/show.html.erb
spec/decorators/sipity/decorators/processing/resourceful_action_decorator_spec.rb

@ed47461f6463d8ac203d1d9333eb0cbb05da6104
@51b8cf60c2946490906fdb8c9ff47899e04cca7c
The current_page? method returns true for the delete URL for the work.

Removing some view logic

---

.gitignore
Gemfile
Gemfile.lock
app/forms/sipity/forms/work_enrichments/attach_form.rb
app/views/sipity/controllers/work_enrichments/attach.html.erb
config/application.yml
config/environments/production.rb
config/environments/staging.rb
config/initializers/dragonfly.rb
spec/forms/sipity/forms/work_enrichments/attach_form_spec.rb

@04380b4101ec964b5234a95ce9e4a6b51ddd9052
This is recommended for the Dragonfly gem, and is an all around good
idea for staging and development.
@579803301e14a537fd78893bca56721abb0cc99a
Again, a recommendation for Dragonfly and caching in general
@fa1cc05190c8b35aa2d9ac472bc0dc55fa3f9d7f
@See http://markevans.github.io/dragonfly/configuration/
@924c3d803d856206b814cb2463e8f1c1d3099490
I want a way to share what are the names of the keys our application
is expecting. This also helps in the bootstrap process for our
application.
As a matter of deploys we update the secrets of our application, so
the keys you find within the config/application.yml are not the real
keys.
@8dc0e4d06d24aabe4dececdaf53d0531e4dfdd8a
This is non-functioning code, but it does expose the correct
attributes for …

Working on attachment

---

app/decorators/sipity/decorators/processing/resourceful_action_decorator.rb
app/exceptions/sipity/exceptions.rb
app/views/sipity/controllers/works/show.html.erb
spec/decorators/sipity/decorators/processing/resourceful_action_decorator_spec.rb
spec/exceptions/sipity/exceptions_spec.rb

@89d4677af854b11748d6cd696edd86508af23500
@e4b367d7d2ed17e7d80c60a4c5fd78435b255e20
As I was working on testing other things, I had a case of a poor
initialization that resulted in weird behavior. This fixes that by
throwing a noisy exception.
@14caf2eb82629603c2b3a7b5499cfdc245e97058
This method is useful for containing the logic regarding a resourceful
action. In theory, we may want to consider a confirmation action
as it relates to the destroy action; For now this will work.
@2fe412635c34f0a5687b11b9b727caa87fcff28c
There is if logic that I'd like to step away from, but for now I'll be
happy to encapsulate the first part of the logic.

Working on exposing the delete action

---

app/controllers/sipity/controllers/works_controller.rb
app/repositories/sipity/commands/work_commands.rb
app/runners/sipity/runners/work_runners.rb
config/locales/en.yml
spec/controllers/sipity/controllers/works_controller_spec.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/runners/sipity/runners/work_runners_spec.rb
spec/support/sipity/command_repository_interface.rb

@b88790b3bf1778e4cca572eac5f91cf8f4cd4991
As identified, we are not able to delete Works; This exposes that
method.
@6dc6e0b3a977de1003143252bebafc4a29109904
Making sure that the resourceful route resolves.
@2e3f552a9b53e538d76660f5669315352c56e003
It is rather trivial to add a repository method, and while it may
appear to be overkill, I'd prefer to have such a "big" concept as
"destroy" be handled by the repository; Because there may be messages
that need to fire.
@abe621ab09ed8b6c7d84f93b4845bc29f78fc7af
Instead of assuming knowledge of the work, I'd rather make sure that
the repository again handles the destruction of the work. In this way
any "callbacks" can be handled.
@c24780017d5bee9a7961a12ddf56c6d14d4ba994
It is helpful to acknowledge that the object was deleted.

Exposing the delete action

---

app/forms/sipity/forms/work_enrichments/attach_form.rb
app/models/sipity/models/attachment.rb
spec/models/sipity/models/attachment_spec.rb

@68f1a61ea01411b45c57d786ac031b9dcbfc0ba6
The incorrect class was at the beginning of the file. This made the
code more confusing.
@2f45288fed87d24a6f09b0b9ac104013d8fb771e
Instead of the less expressive object, refering to it as an
attachment.
@ed6ac1c151a1dc2e15ac180243f84e06ed4c3e3b
This method is to help a simple wrapping element not need to be so
very nosy about its neighbor.
@700713c79645ba577031b71e298e1b2914bdd213
Instead of digging deep into an attachment, I'm exposing the basic
information that I need.
@d3b74b14d8769b8c619a0a3f9bcab52fe96fc1f2
This object helps in the collaboration of form building and rendering.
Its primary function is to expose a `#delete` attribute along side a
handful of methods to help render an HTML form.

Restoring test coverage

---

app/conversions/sipity/conversions/convert_to_boolean.rb
app/forms/sipity/forms/work_enrichments/attach_form.rb
app/repositories/sipity/commands/work_commands.rb
spec/conversions/sipity/conversions/convert_to_boolean_spec.rb
spec/forms/sipity/forms/work_enrichments/attach_form_spec.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/support/sipity/command_repository_interface.rb

@3811514e9b43cd6c5194f34fa8df98615fbc093b
So we can delete enmasse
@031cabed012dc5d70043fbd77f98de742d3758b7
The present form implies that we can update the metadata (i.e. name
of the attached file). However, deletion is more important.
@8c6a4ba5296c183a07edc9e66c8d0dd8fc2b39ef
> Exposes a conversion method to take an input and transform it into a
> boolean. This is important because user input can come in the form
> of 'true', 'false', '0', '1'.

Adding ability to modify attachments

---

app/models/sipity/models/work.rb
spec/repositories/sipity/commands/todo_list_commands_spec.rb
spec/repositories/sipity/queries/enrichment_queries_spec.rb

I continue to expose the Work#processing_state as a matter of
convenience. However the ability to write the processing_state is
removed.

Removing usage of deprecated method

---

app/forms/sipity/forms/work_enrichments/attach_form.rb
app/repositories/sipity/commands/work_commands.rb
spec/forms/sipity/forms/work_enrichments/attach_form_spec.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/support/sipity/command_repository_interface.rb

@d264b67a4119aa4a1c21729c0670a3c7aedc302d
In the AttachForm, I want to keep commands happening at the same level
of abstraction. This means that I do not handle array wrapping in the
form but instead push down to the repository.
@f8d73f27b7db39979de97ef2f38811a2a215b485
Given that a user may want to change the name of the file
Then a means of capturing and persisting those changes must exist

Reworking attach files

---

app/decorators/sipity/decorators/emails/advisor_requests_change_decorator.rb
app/forms/sipity/forms/etd/advisor_requests_change_form.rb
app/mailers/sipity/mailers/email_notifier.rb
app/views/sipity/mailers/email_notifier/advisor_requests_change.html.erb
spec/decorators/sipity/decorators/emails/advisor_requests_change_decorator_spec.rb
spec/forms/sipity/forms/etd/advisor_requests_change_form_spec.rb
spec/mailers/sipity/mailers/email_notifier_spec.rb

@27ea55263f170b9769f986337ccffc847526acb0
Instead of the entity, of which we won't know what is the processing
comment, I'm opting to send the processing comment.
@ef3342fdf03914e071b1f4a1e67af89a6328b43a
[skip ci]
@f4aaed26b38e081e92b8474596a85e42ab51f36b
@6ac495b4c1dd52aa7f39c26bad6c4b6a1870169d
This is a requirement as we want to render a comment specific email.
So we will extract that information from the processing comment and
present it as appropriate.
@322b879974e2e6dc1daa85dc86dca9285eaed0ab
The one-size fits all decorator does not fit (but was helpful to get
us addressing the next important updates).
This is splicing in the new Email::AdvisorRequestsChangeDecorator.
@cf2fecf49f8bccfe4a8d71df46d851365c02c89b
Wiring in the required retrieval information

Working on advisor requests change form

---

app/models/user.rb
app/repositories/sipity/commands/work_commands.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/support/sipity/command_repository_interface.rb

Given that Devise is creating the user, and a Grad Student can create
a user, I'm wanting to make sure that we have emails.
Without emails, the system will start throwing errors when emails are
sent.

Ensuring that User#email is set

---

app/models/sipity/models/simple_controlled_vocabulary.rb
db/migrate/20150304150208_create_sipity_models_simple_controlled_vocabularies.rb
db/schema.rb
spec/models/sipity/models/simple_controlled_vocabulary_spec.rb

> Responsible for defining what values are allowed for a given
> predicate.
>
> @todo - Convert Sipity::ModelCollaborators#role to use controlled
>   vocabulary based on work type. That will be important once we have
>   collaborator's roles vary by work type (i.e. does a Doctoral
>   Dissertation have different roles from a Master's Thesis, or from
>   a Conference Presentation).
>
> @note - At present the controlled vocabularies do not vary based on
>   any work type; However that is one potentiaul future variance.

Adding model for SimpleControlledVocabulary

---

CONTRIBUTING.md
README.md

> There are a number of advantages to writing unit tests that never touch the database.
> The biggest is probably speed of execution - unit tests must be fast for test-driven development to be practical.
> Another is separation of concerns: unit tests should be exercising only the business logic contained in your models, not ActiveRecord.
>
> From [nulldb gem](https://github.com/nulldb/nulldb)
[skip ci]

Explaining goal of minimal DB hits

---

app/forms/sipity/forms/etd/submit_for_review_form.rb
config/locales/en.yml
spec/features/sipity/trigger_work_state_change_spec.rb
spec/forms/sipity/forms/etd/submit_for_review_form_spec.rb

Given that a grad student may be depositing all kinds of material, we
need to confirm with them that they are submitting documents to which
they have a right to submit.

Requiring user to aggree to Terms of Deposit (ToD)

---

app/forms/sipity/forms/work_enrichments/collaborator_form.rb
app/models/sipity/models/collaborator.rb
app/repositories/sipity/commands/work_commands.rb
app/views/sipity/controllers/work_enrichments/collaborators.html.erb
spec/forms/sipity/forms/work_enrichments/collaborator_form_spec.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/support/sipity/command_repository_interface.rb

@ded05e7d54ec0c975e873be997635cc09ff93ec2
> Responsible for adding collaborators to the work and removing anyone
> else.
@fef6d891a8f8cdd551bebca2328c01e69a0b6b6a
Since we have the repeater field, I'm making an assumption. If the
user removes the collaborator via the remove button in the UI, then
I will delete that collaborator.
@1745a1df4782c8d1658805a0eeb154a5c05585d3
Unlike a user and a group, a collaborator-based actor is much more
transient; That is to say Sipity is exposing a user based means of
getting rid of collaborators.
@99bdd817b4fbbea803a36ebf8cc738dc5c635048
As per @danhorst's TODO items, I'm moving the building an extra
collaborator logic down into the form.
Also, don't worry about stripping away extract empty rows from the UI.
It is being [handled …

Working on ability to delete collaborators

---

Gemfile
Gemfile.lock

Paired with the [RailsPanel](https://github.com/dejan/rails_panel)
Chrome Extension, I can get lots of information related to rendering
and queries.
> The first columns gives you the HTTP Response Status, the Controller
> and Action that your route hit, the HTTP Verb (PUT/POST/GET),
> request format (HTML, JSON, XML) and the response time. These
> metrics by itself would have been quite valuable, but there is more.
> You can click on any request that you made and see more information
> about it.
>
> ...
>
> The next tab is the Rendering which gives a breakdown of all the
> views being rendered. This is useful for finding which partials are
> taking the longest to render. Click on the view name automatically
> opens it in your editor.
Discovered from the following blog post: …

Adding meta_request gem

---

app/forms/sipity/forms/work_enrichments/attach_form.rb
app/models/sipity/models/attachment.rb
app/repositories/sipity/queries/processing_queries.rb
app/services/sipity/services/authorization_layer.rb
app/views/sipity/controllers/work_enrichments/attach.html.erb
config/initializers/dragonfly.rb
spec/models/sipity/models/attachment_spec.rb
spec/repositories/sipity/queries/processing_queries_spec.rb
spec/services/sipity/services/authorization_layer_spec.rb

@d7b09a2bc13aec22165c3a9c2c8bf669e3f3e933
@bb8f42a233b480ca2d5efda93afdce17c922d922
So that a user can download the attachment, I want to expose a means
of accessing that.
@d9c00251e40fe912eabddd56689e8d9a72b7fab7
Prior to this commit, the URL for any attachment was publicly
accessible. And while it may have been hard to determine what the URL
should have been, it is something that could easily be disclosed (on
accident).
With this change, authorization is enforced on an attachment. It is a
quick fix and may not reflect the ideal situtation, but it is a better
approximation of what we need.
NOTE: Due to Dragonfly's caching if the policy enforcement changes it
is possible a user that once had access (but should no longer) will
still have access.
@e94e2e549ae1325c4d8612f72bfa7923f0900fdc …

Working on ensuring that attachments have policy enforcement applied

---

Rakefile
config/deploy.rb
config/environment_bootstrapper.rb
lib/tasks/sipity.rake
scripts/update_secrets.sh

@756c7aaa9dd98b9b24136ee11c71c97e4c8ed1f6
Moving the existing rake task into an environment_bootstrapper.rb
Why config? Because secrets drops all of that information in config.
@d7b842122b39529d4ea7c7882d2f3e55f4fd37ec
I need a way, at least for the short-term, to manage environment
specific data entries; Both create and update. This is that
communication change vector.
I would prefer to have a robust administrative interface.
@4812dcd5cfcfd50829d566e1968e5997a9ee0a80
I don't want to auto-assume environment bootstrapping with db:seed; I
don't know the impact on Travis's builds. However, I do want to be
able to add environment specific data entries.
This is perhaps a stop gap as we don't have an administrative
interface concerning the application.

Adding secret seeds to mix

---

app/models/user.rb
spec/models/user_spec.rb

Because of the unique constraint on User#email, when we receive an
empty email for user (e.g. the user form that was filled out had blank
spaces for the given email), blank that out.

Treating blank User#emails as nil

---

app/views/sipity/controllers/works/show.html.erb

Instead of treating predicates as key value pairs, group each
identical predicate and render the values as lists.

Rendering multiple values as list items

---

app/forms/sipity/forms/work_enrichments/degree_form.rb
spec/forms/sipity/forms/work_enrichments/degree_form_spec.rb

When a user enters data via the form, if they are using the multi-
select options, it is possible that we will receive blank entries.
So as part of setting the values, I'm only keeping those values that
are present.

Adding #to_array_without_empty_values

---

app/exceptions/sipity/exceptions.rb
config/application.rb
public/401.html
spec/exceptions/sipity/exceptions_spec.rb

@9f6af8ae0e165dcc39adf73da9046e07a6c36941
These are exceptions that were used in previous iterations but are no
longer relevant.
@a4e0e0c8b6e0b34e11412d395066753d2a866b10
> * config.action_dispatch.rescue_responses configures what exceptions
>   are assigned to an HTTP status. It accepts a hash and you can
>   specify pairs of exception/status.
>
> From http://guides.rubyonrails.org/configuring.html#configuring-action-dispatch
@6dcf0bd342cb9c7ac5ef8934e3a329bb43e7bca8
Instead of a crazy 500 exception error, I'm opting to provide an
unauthorized page 401 page. This is inadequate, but something we can
proceed with in a meaningful way.

Working on exception handling

---

app/services/sipity/services/ldap_client.rb
config/initializers/figaro.rb

> If a particular configuration value is required but not set, it's
> appropriate to raise an error. With Figaro, you can either raise
> these errors proactively or lazily.
>
> To proactively require configuration keys:
>
> ```ruby
> # config/initializers/figaro.rb
> Figaro.require_keys("pusher_app_id", "pusher_key", "pusher_secret")
> ```
> If any of the configuration keys above are not set, your application
> will raise an error during initialization. This method is preferred
> because it prevents runtime errors in a production application due
> to improper configuration.
>
> From https://github.com/laserlemon/figaro#required-keys

Adding requirement for Figaro keys

---

app/models/sipity/models/collaborator.rb
config/locales/en.yml
spec/models/sipity/models/collaborator_spec.rb

Disallowing @nd.edu email addresses so as to push people towards
providing a valid NetID.

Adding Collaborator#email validation

---

.hound.yml
app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb

Also, switching to use translations instead of hard-coded strings.

Restoring test coverage at the unit level

---

app/controllers/sipity/controllers/work_enrichments_controller.rb
spec/controllers/sipity/controllers/work_enrichments_controller_spec.rb

Prior to this commit, when I submit the form, if I do not provide an
attached file, the application throws an exception. These changes are
now allow for an empty form to be submitted.
Closes #247

Allow for :work parameter to be skipped

---

app/forms/sipity/forms/work_enrichments/describe_form.rb
app/repositories/sipity/commands/additional_attribute_commands.rb
spec/forms/sipity/forms/work_enrichments/describe_form_spec.rb
spec/repositories/sipity/commands/additional_attribute_commands_spec.rb

@0f07878397aa3dd04cf00e224c4522bf240b37ae
Instead of using Queries::AdditionalAttributeQueries, prefer an
instance method.
@f741f2c4c30efdaccde68f442408a09c30220073
These methods are not necessary as a public method.
@f0d67b808cff9bd5cde56b8e15cd4af9329ab0de
@8b97a65ee8871d6ff89be3fd1d177e7cb73ac329
Skolemize all the things!
Closes #250

Ensure that only attributes that are present are persisted

---

app/views/sipity/controllers/work_enrichments/describe.html.erb

Given that the discipline is required but the alternate title is not,
present the discipline first then alternate title.
[skip ci]

Rearranging presentation order of fields

---

.hound.yml
app/forms/sipity/forms/create_work_form.rb
app/mailers/sipity/mailers/email_notifier.rb
app/views/sipity/mailers/email_notifier/confirmation_of_entity_created.html.erb
spec/forms/sipity/forms/create_work_form_spec.rb
spec/mailers/sipity/mailers/email_notifier_spec.rb

Send notification to creating user when creating a work
Add email notifier method and script for confirmation_of_entity_created
Spec to verify nofication on create form and verify notifier sends email
Closes #270

Issue #270 - Email should be sent to creating user when the work is first created

---

app/conversions/sipity/conversions/convert_to_work.rb
app/decorators/sipity/decorators/email_notification_decorator.rb
app/exceptions/sipity/exceptions.rb
app/mailers/sipity/mailers/email_notifier.rb
app/services/sipity/services/advisor_signs_off.rb
app/views/sipity/mailers/email_notifier/ready_for_grad_school_review.html.erb
spec/conversions/sipity/conversions/convert_to_work_spec.rb
spec/decorators/sipity/decorators/email_notification_decorator_spec.rb
spec/mailers/sipity/mailers/email_notifier_spec.rb
spec/services/sipity/services/advisor_signs_off_spec.rb

@b71deed80cada0aed5f217e3646eaa513e056b18
The current solution is a bit confusing. This is a first step to
clarify that most emails are related to the given work.
@982458da33740e4346266d004be9064b7269525a
Given that I am always working with polymrophic things and composed
objects, I want a means of getting an object's work.
@c02e07f13a8a4a370988d7641b0a4727da2a5e4c
Instead of the localized method, rely on a more centralized converter.
@2cbb06270e3cd4ef1e6165ea8fe20f3c0e394205
The email that was previously being sent was confusing as it was
related to an incorrect state.
Closes #273

Working on email notification behavior

---

Rakefile
config/locales/en.yml
lib/tasks/sipity.rake

> We bypass I18n in the test suite to speed things up but we depend
> on it a lot for the application. This is ordinarily fine but
> introduces some risk.
>
> For example @78cb09d introduced a syntax error into the YAML file
> but it did not cause any tests or validations to fail. This kept the
> build passing but the application could no longer render any pages.
>
> From #290
Closes #290

Adding build task to validate I18n files

---

app/models/sipity/models/processing/strategy_action.rb
db/migrate/20150311145535_adding_presentation_sequence_to_strategy_action.rb
db/schema.rb
db/seeds.rb

> Given that certain required tasks make "more sense" to be done
> first, we need to specify a presentation sequence order. This will
> ensure that rendered todo list actions come back in the same order.
> It will also ensure that we have control over the sequence of state
> advancing buttons, etc.
Closes #294

Adding PresentationSequence to strategy_actions

---

config/deploy.rb
config/deploy/pre_production.rb

BRANCH_NAME env is required to deploy a branch

Capistrano should take BRANCH_NAME for deploy

---

app/forms/sipity/forms/work_enrichments/collaborator_form.rb
spec/forms/sipity/forms/work_enrichments/collaborator_form_spec.rb

When a form is submitted incomplete attributes, those were sometimes
being expunged. The resulting form was invalid. When the form would
re-render, it would no longer have a blank collaborator row.
Closes #301

Ensuring at least one collaborator is returned

---

app/forms/sipity/forms/work_enrichments/collaborator_form.rb
spec/forms/sipity/forms/work_enrichments/collaborator_form_spec.rb

There were a few moving parts in this; First we want to make sure that
we are always rendering enough input fields for the user. Second, due
to changes in how we render collaborators on the form, there was an
unintended side-effect of attempting to persist those collaborators
via the repository.
The solution is to explicitly persist the collaborators_from_input
to the repository; Hence the name changes.
Also clarifying the intent of a guard method:
```ruby
reject_because_an_empty_row_was_submitted_via_user_input?
```
The above method I believe is more clear in its intent.
Closes #311

Ensuring we only attempt to persist user input

---

app/views/sipity/controllers/works/show.html.erb

```cucumber
Given that the content in the Submission Overview pane extends below the bottom of the screen
When I am a depositor
Then there is no indication where the "Submit for Review" button is on the page.
```

Rerranging state advancing action buttons again

---

app/conversions/sipity/conversions/convert_to_processing_action.rb
app/forms/sipity/forms/etd/signoff_on_behalf_of_form.rb
app/models/sipity/models/processing/entity_action_register.rb
app/repositories/sipity/queries/processing_queries.rb
app/services/sipity/services/advisor_signs_off.rb
spec/conversions/sipity/conversions/convert_to_processing_action_spec.rb
spec/forms/sipity/forms/etd/signoff_on_behalf_of_form_spec.rb
spec/models/sipity/models/processing/entity_action_register_spec.rb
spec/repositories/sipity/queries/processing_queries_spec.rb
spec/services/sipity/services/advisor_signs_off_spec.rb
spec/support/sipity/command_repository_interface.rb
spec/support/sipity/query_repository_interface.rb

@35a64eb748b6221d022136e8f20803b4d62a5bd1
Given that two separate actions are being called, I need to ensure
that both the actual action (Signoff on Behalf) is registered and
the related action (Advisor Signoff) is registered. Without both of
those, the state advancement query won't work without other crazy
data modifications.
@08d342d7a4c808bb8a7892ce67b4f3af3697d6ea
Prior to this commit, any collaborator that was identified by email
was always considered to have taken the given action.
This commit makes sure the same logic for determining if a user has
taken an action is applied to the has a non-user collaborator taken
the action.
Closes #252
@0da6ca5223c14e85020cdfd9836a938f1c6b35ee
A registered action is something that can easily be converted to
a processing action. So I need to do …

Signoff on behalf of fails to advance if it is the last person

---

app/decorators/sipity/decorators/emails/work_email_decorator.rb
app/views/sipity/mailers/email_notifier/confirmation_of_entity_created.html.erb
spec/decorators/sipity/decorators/emails/work_email_decorator_spec.rb

Normalizing on work_type instead of document_type; I suppose document
type might be more applicable, but this feels better.

Removing deprecated method usage

---

app/forms/sipity/forms/work_enrichments/access_policy_form.rb
spec/forms/sipity/forms/work_enrichments/access_policy_form_spec.rb

> When a user fills out the access rights for the given work, the date
> is auto-populated. However, it should be discarded before
> preservation if a non-embargo access right is specified.
Why did I choose to put this in the form? Because the form
encapsulates the business logic.
Question: Does it make more sense in the model? Knowledge is bleeding
out of the data structure.
Closes #327

Nullifying input release_date when not an embargo

---

app/assets/stylesheets/modules/_attributes.css.scss
app/decorators/sipity/decorators/work_decorator.rb
app/models/sipity/models/access_right_facade.rb
app/views/sipity/controllers/works/show.html.erb
spec/decorators/sipity/decorators/work_decorator_spec.rb
spec/features/sipity/enriching_a_work_spec.rb
spec/models/sipity/models/access_right_facade_spec.rb

@d34bb1fd13929c345ece721ecc4df35e4b9e177a
I want to be able to render the accessible objects on the view, so
this is the first step.
@30f540b93e6d59175cc0b77eee308280850740f9
Given that we need a way for advisors to review the pertinent
information regarding an object, we need a way to display that
information.
Closes #317

Show reviewers sufficient information that they can make decisions about a submission

---

app/decorators/sipity/decorators/work_decorator.rb
app/runners/sipity/runners/citation_runners.rb
app/runners/sipity/runners/work_enrichment_runners.rb
app/views/sipity/controllers/citations/new.html.erb
app/views/sipity/controllers/dois/assign_a_doi.html.erb
app/views/sipity/controllers/dois/doi_not_assigned.html.erb
app/views/sipity/controllers/dois/request_a_doi.html.erb
app/views/sipity/controllers/work_enrichments/access_policy.html.erb
app/views/sipity/controllers/work_enrichments/attach.html.erb
app/views/sipity/controllers/work_enrichments/collaborators.html.erb
app/views/sipity/controllers/work_enrichments/defense_date.html.erb
app/views/sipity/controllers/work_enrichments/degree.html.erb
app/views/sipity/controllers/work_enrichments/describe.html.erb
app/views/sipity/controllers/work_enrichments/search_terms.html.erb
app/views/sipity/controllers/works/edit.html.erb
app/views/sipity/controllers/works/new.html.erb
spec/decorators/sipity/decorators/work_decorator_spec.rb
spec/views/sipity/controllers/works/new.html.erb_spec.rb

@30b603d1b705b307a257e06c7eb6e6016f556468
This was a kludge and resulted in decorating an object within the
repository methods; Something that I want to avoid. So I'm attempting
to streamline the behavior.
@8656e5c58d40668b460c2a5b583ad8a78cbc163d
These extra DOM classes were chatty and by appearance nothing was
contingent on their presence.

Removing with action pane

---

app/models/sipity/models/access_right_facade.rb
app/views/sipity/controllers/works/show.html.erb
spec/models/sipity/models/access_right_facade_spec.rb

Prior to this commit, I was only rendering an accessible object
without a link/reference to its location.
Closes #350

Exposing the access_url for accessible object

---

.hound.yml
app/forms/sipity/forms/work_enrichments/attach_form.rb
app/repositories/sipity/commands/todo_list_commands.rb
app/services/sipity/services/action_taken_on_entity.rb
spec/forms/sipity/forms/work_enrichments/attach_form_spec.rb
spec/repositories/sipity/commands/todo_list_commands_spec.rb
spec/repositories/sipity/queries/processing_queries_spec.rb
spec/services/sipity/services/action_taken_on_entity_spec.rb
spec/support/sipity/command_repository_interface.rb

@6b140203b28169b97267548b2d1911014d9a4b3d
I want a .register and .unregister command, so I'm refactoring the
class name to account for this.
@96faf08b64c0fedd5942f129b4dd92761a73cdb0
Since I want to both register and unregister an action, I want to
reflect that capability via the method name.
@7c653c3b575933f4970a447d059da27b706ebdfc
There is a case in which I need to reset that an action was taken; I
upload files, then assign access rights, then upload new files. I need
to make sure the access rights are properly assigned again.
@d360107b330059b64183cd7cfd0d6e5927b8e79a
@c13a560e6d6eecf960c656eb070c6e8c00f4ebae
```gherkin
Given that I have three attachments
And I have assigned access rights to each attachment
When I add a new attachment
Then the todo item for the access rights is no …
```

354 when appending attachments reset the must do state for access rights

---

app/forms/sipity/forms/work_enrichments/access_policy_form.rb
app/forms/sipity/forms/work_enrichments/attach_form.rb
app/repositories/sipity/commands/work_commands.rb
app/repositories/sipity/queries/attachment_queries.rb
app/views/sipity/controllers/work_enrichments/access_policy.html.erb
app/views/sipity/controllers/work_enrichments/attach.html.erb
config/locales/en.yml
spec/forms/sipity/forms/work_enrichments/access_policy_form_spec.rb
spec/forms/sipity/forms/work_enrichments/attach_form_spec.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/repositories/sipity/queries/attachment_queries_spec.rb
spec/support/sipity/command_repository_interface.rb

The original ticket said to move the attribute; However, I have opted to instead render it on both forms.
@178f31ff6416a145a3abc19f71f11dc107b689d1
Instead of returning an ActiveRecord::Relation return the found
object, if applicable.
@5e2a74aef9f617855a8d08b6b7ba5985bd4c2821
This involves exposing validation and retrieval.
@e78b397335f2e286b8d738a0805b2324128acf83
@ec85642cc11faa5684daa42356ff4b99956fec09
This method is used for building the select criteria.
@e93ab5306f89c30ad6b26aa8338d1b08a63ce053
To reduce confusion on an attribute for a form and a repository
method, I am opting to rename this.
I then want to rename the attribute :mark_as_representative to
:representative_attachment_id
@d50db3d93dbe8faf08c800d9ee796e85821531eb
I have found the name confusing. Mark as representative …

Move mark as representative to the access policy form

---

Rakefile

The 100% is a configurable options.
What I mean by code is `.rb` files in the `app` or `lib` directory.
As this is a goal under discussion (see #372), and one that can be
enforced, I'd like to advocate for automated enforcement.
First: It is a configurable value; If we find that 100% is to
aggressive we can dial that back. We already have 100% coverage, so
keeping to that is less expensive than on code bases we are picking up
to maintain.
Second: My goal for the group is to still push towards Test Drive
Development; I understand the reality of the learning curve for
testing. However, as a reviewer of the code I would like to leverage
any and all tools available to help in the review process. One of
those is making sure that new code is tested; Code coverage is, in my
estimation, a proxy …

Enforcing that less than 100% code coverage breaks the build

---

Gemfile
Gemfile.lock

@23b339615e61936b6a608b765ae1829de7ea790c
I was using this gem to model state machines, but since I've pushed
those concerns into the database, this is no longer needed.
@b694abb8a346c86eb517801dc0faa4029f6f38aa
By using the Hesburgh API, we no longer need the net-ldap gem.

Removing unneeded gems

---

.travis.yml
Gemfile

* Rails 5 will require Ruby 2.2.1 and greater
* There are notable performance increases in Ruby 2.2.1 vs. Ruby 2.1.5

Loosening Ruby vesrion requirement

---

Gemfile
Gemfile.lock

This is not necessary for our current ecosystems

Removing unicorn usage

---

app/forms/sipity/forms/create_work_form.rb
app/repositories/sipity/queries/work_queries.rb
app/runners/sipity/runners/work_runners.rb
config/locales/en.yml
spec/forms/sipity/forms/create_work_form_spec.rb

@c728b4d61998ece6532adae6f83cdbd51aa3519a
With this commit, the CreateWorkForm is more like the other forms in
the application.
@27c0691e14e23fd7ff2c48fbaeaa4050caa385e1
The method complexity had become too high, so I needed to tease apart
the form submission.
@73bdd346cb574453f664ce82c0622e08ec3dd28f
This removes some of the chatter from the form, and helps keep the
concern more narrow.
@94ac3f4d32b228716909550b2068207c877491fe
This is a hold over from a previous setup; we don't need it.

Normalizing create work services

---

spec/decorators/sipity/decorators/processing/base_decorator_spec.rb
spec/decorators/sipity/decorators/processing/resourceful_action_decorator_spec.rb

The following message has been around for quite awhile. Getting rid of
it.
```console
resourceful_action_decorator_spec.rb:7: warning: already initialized
constant Sipity::Decorators::Processing::ENTITY_ID
base_decorator_spec.rb:7: warning: previous definition of ENTITY_ID
was here
```

Removing already initialized warning for specs

---

app/forms/sipity/forms/work_enrichments/access_policy_form.rb
app/forms/sipity/forms/work_enrichments/attach_form.rb
app/repositories/sipity/commands/work_commands.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/support/sipity/command_repository_interface.rb

Detected a warning in Ruby 2.2.1
```
warning: circular argument reference - user
```

Removing unused parameter from method

---

.gitignore
Gemfile
Gemfile.lock
Rakefile

@03ca9af50f920884a48fd833b01b4e5c3f63c66d
$ bundle install
> Brakeman is a static analysis tool which checks Ruby on Rails
> applications for security vulnerabilities.
>
> https://github.com/presidentbeef/brakeman
I am interested in making this part of the build; If there are
vulnerabilities the build should be considered broken.
@d3e87a5efb0a2c342d22ccc32c26d5405847f81f
Brakeman is a static anaylsis security vulnerability scanner. It can
find potential vulnerabilities in our code. By adding this task as
part of the Travis build it is one more means of claiming ownership of
our application.
@1eb691e891c2ec543bfc6418f4be4bf3362f44b9
This is already locally enforced, but via an oversight it was skipped.
Closing that loop.
@7c9bc8667d793da0f4516a2d7144d5791a725c58
This command was running …

Adding brakeman for vulnerability scanning

---

app/decorators/sipity/decorators/work_decorator.rb
app/forms/sipity/forms/work_enrichments/access_policy_form.rb
app/repositories/sipity/queries/simple_controlled_vocabulary_queries.rb
spec/decorators/sipity/decorators/work_decorator_spec.rb
spec/forms/sipity/forms/work_enrichments/access_policy_form_spec.rb
spec/repositories/sipity/queries/simple_controlled_vocabulary_queries_spec.rb
spec/support/sipity/command_repository_interface.rb
spec/support/sipity/query_repository_interface.rb

@333126beeff5ac7eb63198634f098dfcb8f8bb2f
I want the controlled vocabulary entries; There is something more
specific going forward.
@44dd946a3e6cf7002ffb8d950b51ed4391656312
I want to get the value based on the controlled vocabulary's predicate
and code.
@c497c1d35f52fb11d659b484289d46c1e946c287
Instead of relying on the decorator performing transformations of data
let it behave as a simple translator of values. This simplifies the
logic and the mocking that is required.

Paying down tech debt

---

app/forms/sipity/forms/work_enrichments/plan_of_study_form.rb
spec/forms/sipity/forms/work_enrichments/plan_of_study_form_spec.rb

Prefering the composable validations instead of the
`validates_presence_of`.
Also removing the the explicit message; We want to lean on
translations instead of hard-coded messages; Keep in mind that
implementors may want those translations to vary (i.e. Dutch Royal
Libraries).
Related to #495 and #505

Adding additional test scenarios

---

app/forms/sipity/forms/work_enrichments/search_term_form.rb
spec/forms/sipity/forms/work_enrichments/search_term_form_spec.rb

Instead of referencing the module functions, instead prefer to use
the collaborating repository object for querying the work's attribute
values.

Replacing explicit module call with collaborator

---

app/models/sipity/models/work_area.rb
spec/repositories/sipity/queries/event_trigger_queries_spec.rb

@56a336549d918f1ef4e6f14c072abd48fd007ec1
When I ran `$ rake spec:coverage:models` I encountered:
```console
./app/models/sipity/models/work_area.rb:15:in `<class:WorkArea>':
undefined method `configure_as_a_processible_entity' for
Sipity::Models::Processing:Module (NoMethodError)
```
This fixes that problem.
@987c5e85b180dcce82da025b2c89fcd1ebc0157a
After running `$ rake spec:coverage:repositories` I saw that the test
coverage was 99.64%. The event_trigger_queries test was missing.

House keeping

---

.travis.yml

Now that we are running 2.2.2 locally, we need not test these other
ruby versions.

Removing ruby build versions for travis

---

config/initializers/power_converters.rb
spec/config/initializers/power_converters_spec.rb

@da7c24c092db05c5cc7e2eca8978996ee3c51d74
The WorkArea is going to inform the module space used for building
forms. As such, I want a way to "quickly" convert an object to the
Work Area.
The main goal is to convert a ProcessingEntity or Work into the
WorkArea, but for now I'm not certain what direction that would be.
There is a clear query path based on the current ERD, but I believe
the ERD may represent the final design as we tease apart the
Submission Window behavior.
@a33de0d84d570720cc212fef6f392c16ede4ba00

Adding power converter for work area

---

app/forms/sipity/forms/work_enrichments/access_policy_form.rb
spec/forms/sipity/forms/work_enrichments/access_policy_form_spec.rb

> NoMethodError:
>   private method `access_right_code' called for
>   #<Sipity::Forms::WorkEnrichments::AccessPolicyForm::
>       AccessibleObjectFromInput:0x007ff3d6e61fa0
>    >

Ensuring method visibility for access policy

---

config/initializers/airbrake.rb

We don't need to know each time someone hits the back button on a task
that they don't have permission to take.
[skip ci]

Skipping reporting of authorization errors

---

app/models/sipity/models/submission_window.rb
app/models/sipity/models/work_area.rb
app/services/sipity/services/create_work_area_service.rb
app/services/sipity/services/find_or_create_submission_window_service.rb
db/seeds/etd_work_area_seeds.rb
spec/models/sipity/models/submission_window_spec.rb
spec/models/sipity/models/work_area_spec.rb
spec/models/sipity/models/work_type_spec.rb
spec/services/sipity/services/find_or_create_submission_window_service_spec.rb

@dac0a6ba4760868311b33146fa14486c77617645
@83515727cafda20a836f904b98b54845fe1efd41
For building a work area, I want it to be based on the slug.
@d69bc0231d1ca5d88c2e7684de3dee1e5ef9ba94
@118f69944262d94d4e9d612af018875d439c0266
Because submission window's have workflows
@ffe730e7634aeedbd9e44f2369e9bc47f0bb7071
Because work area's have workflows
@275e3c4dea2f3f02c0d0fae1a7f0f13cf0da1fd9
Because work type's have workflows
@b7d7e8786ab6aa4d1302319e77f52ae465c2b718
I want to begin encoding the "factory" services (perhaps a new
directory) for what happens when we want to create a new submission
window.
@c25d15d7377b2ac8a8f90f82175661d5f78de8ef
Instead of assuming I have a work area, convert the value to a work
area.
@dc9b29019798b2c88c2b7f9496c2cf844e6fa0a4
I still need to resolve the …

Reworking create work area

---

app/data_generators/sipity/data_generators.rb
config/application.rb

> Sipity levereages a lot of data-driven configuration. This module is
> a place to provide classes and infrastructure for bootstrapping the
> configuration related data entries.
>
> ## Why Not Factories?
>
> Because of the ubiquitous FactoryGirl, I am avoiding the name of
> Factory. In using the term DataScaffolds I hope to convey that these
> more closely resemble a rails generator; In other words, use the
> data generators to help bootstrap the application.

Adding DataGenerators module

---

app/data_generators/sipity/data_generators.rb
app/data_generators/sipity/data_generators/find_or_create_submission_window.rb
app/data_generators/sipity/data_generators/find_or_create_work_area.rb
app/data_generators/sipity/data_generators/find_or_create_work_type.rb
app/models/sipity/models/work_area.rb
app/services/sipity/services/create_work_service.rb
db/seeds/etd_work_area_seeds.rb
spec/data_generators/sipity/data_generators/find_or_create_submission_window_spec.rb
spec/data_generators/sipity/data_generators/find_or_create_work_area_spec.rb
spec/data_generators/sipity/data_generators/find_or_create_work_type_spec.rb
spec/features/sipity/interacting_with_a_work_area_spec.rb
spec/fixtures/seeds/scope_processing_entities_for_the_user_and_proxy_for_type.rb
spec/services/sipity/services/create_work_service_spec.rb

@32c2d6fecbbbc9b6a5bc0d7afa9d689b4499f9fb
[skip ci]
@87254da8d477f5193402043e1c2a301d1ddb6457
Instead of having these objects sit amongst the "services bucket", I
want to sequester them into their own space.
Objects in the DataGenerators module are present for "bootstrapping"
via a developer/sys admin's command line; They represent the necessary
steps to bootstrap a viable ecosystem.
Yet they are not seeds; They encompass the logic required to get
certain "foundational" elements up and running. They also represent
a crease in the code that will allow us to craft plugins for new
Work Areas, Submission Windows, and Work Types.
@274c80894b0c426e38ce019ebb0efa756fd37734
Instead of having these objects sit amongst the "services bucket", I
want to sequester them into their own space.
Objects in …

Adding app data generators module

---

config/locales/en.yml

Instead of a non-html version, I want to use the translated HTML.
Because we had a key of :access_changes_over_time the SimpleForm
rendering was treating the value as not HTML safe and was escaping
the <i> and </i> tags. By using :access_changes_over_time_html
SimpleForm treats the I18n value as HTML Safe and thus does not escape
the <i> and </i> tags.

Updating access_changes_over_time I18n

---

config/routes.rb
spec/routing/submission_window_routing_spec.rb
spec/routing/work_area_routing_spec.rb

Instead of the "privileged" actions of "edit", "create", etc I'm going
with the more generalized query_action and command_action. This will
mean the forms that are generated may need some TLC as Rails makes
grandiose assumptions/conventions regarding pathing of objects.
However, this will push towards a more normalized experience via both
routes and controllers.

Tidying up routes for WorkArea & SubmissionWindow

---

app/repositories/sipity/queries/submission_window_queries.rb
app/repositories/sipity/queries/work_area_queries.rb
app/repositories/sipity/query_repository.rb
spec/repositories/sipity/queries/submission_window_queries_spec.rb
spec/repositories/sipity/queries/work_area_queries_spec.rb
spec/support/sipity/command_repository_interface.rb
spec/support/sipity/query_repository_interface.rb

Instead of overworking the WorkAreaQueries, I want a separate query.
This is in preparation for SubmissionWindow action rendering.
Once the SubmissionWindow action rendering is complete, I can bring
that to the ETD work space.
The goal is to move quickly on it so I can add the requisite new
actions.

Extracting a proper SubmissionWindowQueries mod

---

app/models/sipity/models/submission_window.rb
app/presenters/sipity/controllers/submission_window_presenter.rb
app/presenters/sipity/controllers/submission_windows/show_presenter.rb
spec/models/sipity/models/submission_window_spec.rb
spec/presenters/sipity/controllers/submission_window_presenter_spec.rb
spec/presenters/sipity/controllers/submission_windows/show_presenter_spec.rb

@2adfaad0730f0c62a50748def6de77220f9ce02f
In preparation for the ULRA work form retrieval normalizing the
underlying elements.
@14b6f8066e78d70fddde64817ae8b6971cfc2c0d
I want to have access to this method without undo antics.
@ae9cffbbfe3baa44c4910ff442f517aa5c81a7d2
Thusfar there has been no violation of the law of demeter
@8b4b6057b62f37374d4bdeacc3da1bcf8c4d96b2
Given that Show is a "glorified use case" of the query actions, I'm
contemplating revoking its highlighted privilege and replacing it with
a query action.

Working on dynamic submission window form retrieval

---

app/exceptions/sipity/exceptions.rb
app/response_handlers/sipity/response_handlers/submission_window_handler.rb
app/runners/sipity/runners/submission_window_runners.rb
spec/exceptions/sipity/exceptions_spec.rb
spec/response_handlers/sipity/response_handlers/submission_window_handler_spec.rb
spec/runners/sipity/runners/submission_window_runners_spec.rb

@6bee7778415e0dce366ebcec89e17409fd0f469d
Consider that I am submitting a form for a submission window to create
a work within that submission window:
* I would expect the returned object to be the work that I submitted
* I would expect to handle that form's response differently than an
update to the submission window.
@67ce71498334496f3c7343e0b6532a0465f0bfb7
@84846a12cde996d047effb340cc36603d8610554
Expanding on the current response handling

Working through response handler

---

.hound.yml
app/decorators/sipity/decorators.rb
app/forms/sipity/forms/core/submission_windows/show_form.rb
app/forms/sipity/forms/core/work_areas/show_form.rb
app/forms/sipity/forms/core/work_submissions/show_form.rb
spec/decorators/sipity/decorators_spec.rb
spec/forms/sipity/forms/core/submission_windows/show_form_spec.rb
spec/forms/sipity/forms/core/work_areas/show_form_spec.rb
spec/forms/sipity/forms/core/work_submissions/show_form_spec.rb

@fcb192108aaa74cffec3e7254144fbd5f27b640c
The rubocop settings were adjusted because these comparison operators
are not-advised by default Rubocop. However, with PowerConverter and
case statements, I need to leverage these behaviors.
@422e02db0c1d9a63d30f18e2d20815fe0319f324
I was running into the case in which PowerConverter could not convert
a ShowForm to the requisite WorkArea or ProcessingEntity.
This now works around that.

Working on general view and template organization

---

app/data_generators/sipity/data_generators/find_or_create_submission_window.rb
app/data_generators/sipity/data_generators/find_or_create_work_area.rb
app/data_generators/sipity/data_generators/submission_windows/base_generator.rb
app/data_generators/sipity/data_generators/submission_windows/etd_generator.rb
app/data_generators/sipity/data_generators/submission_windows/ulra_generator.rb
app/data_generators/sipity/data_generators/work_areas/base_generator.rb
app/data_generators/sipity/data_generators/work_areas/etd_generator.rb
app/data_generators/sipity/data_generators/work_areas/ulra_generator.rb
app/data_generators/sipity/data_generators/work_types/etd_generator.rb
app/data_generators/sipity/data_generators/work_types/ulra_generator.rb
app/forms/sipity/forms/etd/start_a_submission_form.rb
db/seeds/groups_and_roles_seeds.rb
spec/data_generators/sipity/data_generators/find_or_create_submission_window_spec.rb
spec/data_generators/sipity/data_generators/find_or_create_work_area_spec.rb
spec/data_generators/sipity/data_generators/submission_windows/base_generator_spec.rb
spec/data_generators/sipity/data_generators/submission_windows/etd_generator_spec.rb
spec/data_generators/sipity/data_generators/submission_windows/ulra_generator_spec.rb
spec/data_generators/sipity/data_generators/work_areas/base_generator_spec.rb
spec/data_generators/sipity/data_generators/work_areas/etd_generator_spec.rb
spec/data_generators/sipity/data_generators/work_areas/ulra_generator_spec.rb
spec/data_generators/sipity/data_generators/work_types/etd_generator_spec.rb
spec/data_generators/sipity/data_generators/work_types/ulra_generator_spec.rb

Instead of work area level modules sitting above application concepts
in the module namespace, I'm switching that.
It keeps similar application concerns closer together.

Reworking data generator organization to match

---

app/data_generators/sipity/data_generators/work_types/etd_generator.rb

Given that the etd_review can request change on behalf of someone,
we no longer need to give the ETD Reviewer permission to submit an
Advisor Requests Change form.
Verified via the graph generated from the state machine.

Removing etd_reviewer permission to action

---

app/exceptions/sipity/exceptions.rb
app/services/sipity/guard_interface_expectation.rb
spec/exceptions/sipity/exceptions_spec.rb

Instead of failing early, I'm collecting all of the interface methods
that the object did not respond to then raising an exception that
includes all of that information.

Updating how interfaces are guarded

---

app/forms/sipity/forms/processing_form.rb
app/services/sipity/guard_interface_expectation.rb
spec/forms/sipity/forms/processing_form_spec.rb
spec/forms/sipity/forms/submission_windows/etd/start_a_submission_form_spec.rb
spec/forms/sipity/forms/submission_windows/ulra/start_a_submission_form_spec.rb
spec/spec_helper.rb
spec/support/sipity/rspec_matchers.rb

@a82b7d17f6d716603af470ebe8b06f698ceca16d
@dd4689db643e88c16a1bdea5fb0c64112212e280
There are some assume interface interactions that I need to make sure
are in place. The next step is to add an RSpec matcher.
@9f9a6b078a843e221e21e9cc14ffca06e9661eef

Tightening up form expectations

---

Gemfile
Gemfile.lock

Yes, twitter as a source for this action:
https://twitter.com/schneems/status/603227060199272448
However, the underlying Issues can be found:
* https://github.com/mime-types/ruby-mime-types/issues/83
* https://github.com/mikel/mail/pull/829

Freeing up RAM by not requiring all mime types

---

app/assets/javascripts/sipity/redactor_field.js.coffee
app/assets/stylesheets/framework_and_overrides.css.scss
app/assets/stylesheets/modules/_panel.css.scss
app/assets/stylesheets/redactor.css
app/views/sipity/_form_panel.html.erb
app/views/sipity/controllers/submission_windows/etd/start_a_submission.html.erb
app/views/sipity/controllers/submission_windows/ulra/start_a_submission.html.erb
app/views/sipity/controllers/work_submissions/etd/describe.html.erb
config/locales/en.yml
db/seeds/controlled_vocabularies_seeds.rb

Implementing some of the feedback from [Randy](http://www.randalseanharrison.com/) on how best to clean up the initial submission page.
- Increased consistency of field labels; changed case of emphasised words to increase contrast
- Option text has been simplified for publishing and patent concerns
- Redundant labeling has been removed
- Grid of panels has been abandoned to improve eye-tracking and content flow
- Removed Redactor controls that should not apply to simple text fields
NOTE: I attempted to change the _order_ of the WORK_PATENT_STRATEGY and WORK_PUBLICATION_STRATEGY options by editing the seeds. I assume we will need to do something extra to make this work in production.

UX improvments

---

app/models/sipity/models/work.rb
app/repositories/sipity/commands/work_commands.rb
db/migrate/20150610170005_adding_primary_key_to_work_submissions.rb
db/schema.rb
spec/repositories/sipity/commands/work_commands_spec.rb

Prior to this commit the following Ruby code threw an exception:
```ruby
> Sipity::Models::WorkSubmission.where(work: work).destroy_all
=> !! #<ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column
'sipity_work_submissions.' in 'where clause': DELETE FROM
`sipity_work_submissions` WHERE `sipity_work_submissions`.`` =
NULL>
```
This is because I didn't have a primary key associated with the table.
I could've opted to use the more appropriate composite_primary_keys
gem, however that adds lots of additional code for a very small gain.
Yes, it would be better to have this be a composite key, but I don't
need to add hundreds of lines of code for this edge case.
https://github.com/composite-primary-keys/composite_primary_keys

Adding primary key to sipity_work_submissions

---

app/policies/sipity/policies/work_policy.rb
app/repositories/sipity/commands/additional_attribute_commands.rb
app/repositories/sipity/commands/notification_commands.rb
app/repositories/sipity/commands/permission_commands.rb
app/repositories/sipity/commands/work_commands.rb
app/repositories/sipity/queries/additional_attribute_queries.rb
app/repositories/sipity/queries/processing_queries.rb
app/repositories/sipity/queries/work_queries.rb
lib/tasks/sipity.rake
spec/policies/sipity/policies/work_policy_spec.rb
spec/repositories/sipity/commands/additional_attribute_commands_spec.rb
spec/repositories/sipity/commands/notification_commands_spec.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/repositories/sipity/queries/work_queries_spec.rb
spec/support/sipity/command_repository_interface.rb
spec/support/sipity/query_repository_interface.rb

@426646c1947b1aaf7562f0b2393ca14299fc77a0
By removing a direct reference to a constant, I'm able to have a more
robust composition.
Also, in looking at Policies::WorkPolicy::Scope.resolve, it was only
used via this single method. That means, I am able to remove a layer
of indirection (and ultimately remove a class).
@484e3aa12f2306ec9dded5b0b26501b3a87fead3
By leveraging dependency injection of a repository parameter for a
repository module, I'm able to get around the indirection of the Scope
object.
This methodology will also enable a removal of a long-standing module
function in a repository method.
@0a64b2059a5e66d2efa5efb48d44c82dc36aada8
@d860fc251dce42334da541043a7bc29d2044807f
These are not needed and create undue points of potention chaos.
@ea02b382a7696485459b837befee4878d66b153c …

Housekeeping

---

Gemfile
Gemfile.lock

For a POST request that included an Attachment, processed by dragonfly,
an exception was encountered in our application logic. That exception
was in turn caught and handled via Airbrake. As part of Airbrake's
cleanup, it attempted to send #collect to the attachment. The
attachment, however, was already closed so #collect failed and threw
an exception.
This thrown exception, IOError, in turn obliterated the original
exception that was thrown by our application. It should be noted
that the current work around is a fork of the v4.3.0..master work
of Airbrake. Once issue 396 is resolved and released in a gem, we
can go back to using the default Airbrake gem.
Related to markevans/dragonfly#271
Related to markevans/dragonfly#271
Related to airbrake/airbrake#397
Related to airbrake/airbrake#396

Reducing chance of Airbrake swallowing exceptions

---

spec/db/seeds_spec.rb

The seeds have some reporting, but I don't want to see all
of that in the RSpec output.

Removing chatter on STDOUT

---

app/runners/sipity/command_line_context.rb
spec/runners/sipity/command_line_context_spec.rb

The Sipity::CommandLineContext is analogue to a Rails controller.
It implements the interface necessary for the require context of
a Sipity::Runners object. This is a work in progress in that there
might be an methods on the context that should be implemented.

Adding a CommandLineContext for running tasks

---

config/deploy.rb

Why:
* Because Sipity is a data driven application and its schema as well
as data are equally important.
This change addresses the need by:
* Adding an `after 'deploy:db_migrate'` hook to ensure
`deploy:data_migrate` is run
[skip ci]

Ensuring update to date data migrations of app

---

.reek.config
Gemfile
Gemfile.lock
app/controllers/sipity/controllers/work_areas_controller.rb
app/services/sipity/services/apply_access_policies_to.rb
app/services/sipity/services/netid_query_service.rb
app/services/sipity/services/noid_minter.rb

@887cd145504e20ca2c7cd5aa5370063f48e94f7f
Why:
* Because we want to avoid smelly code.
This change addresses the need by:
* `$ reek app/` to see what Reek identifies as possible code smells.
@0a2a11c29a5189f540fa2525ba160155e315179f
In addition to leveraging Rubocop, I want to explore the automation
and analysis provided by [reek](https://github.com/troessner/reek).
There is some overlap between what Rubocop detects and checks for,
versus what reek looks for.
```console
$ bundle exec reek -c .reek.config app/
```
@c88e862215e5d8f557a759174514426aa29affc0
Responding to the following message:
```console
Sipity::Controllers::WorkAreasController#query_or_command_attributes
calls Kaminari.config 2 times (DuplicateMethodCall)
```
@bd03772fa55a5a57372d6dfd10f5827ae48aa6ea
```console …
```

Updating according to reek

---

Gemfile
Gemfile.lock

@ead5f3f5373dade109c0438d4b92034dfdb3778b
Looking at the output of flay. Ideally, we would work towards
eliminating duplicate method logic. For now, I believe the best
threshold is to observe if we have introduced more duplication.
At present, there are 45 detected duplicates. Perhaps set a
configuration to not allow duplication. Then also set a goal to
eliminate some of that duplication.
```console
$ bundle exec flay app/
```
@f440d7081f80fbe016bec0e3f95544ecdd7dabfe
I don't believe this is something that we would auto-analyze; Though
perhaps we would say that the average of the top 10 flogged scores
should not increase?
Regardless the tool is in place:
```console
$ bundle exec flog app/
```

Adding flog and flay

---

Gemfile.lock
scripts/update-dependency

@473e42afeb5822663fc685df45b0e2a62f5e9080
`$ ./script/update-dependency rails_layout`
@3716a25402d7461a56397c8e4fbfd67512cf5c75
`$ bundle update`
@90681a421dae549ed932eb1b46ce880be92dfd1f
I want Git commit message regarding the underlying script to parse as a
shell command. Thus I added the surrounding backticks (`).

Updating dependencies

---

app/jobs/sipity/jobs.rb
app/jobs/sipity/jobs/etd/bulk_ingest_job.rb
app/models/sipity/models/attachment.rb

I went through a handful of simple yet not entirely obvious steps for
testing the ETD production data for bulk ingest. This commit adds the
information needed to run those tests.
[skip ci]

Adding documentation on ETD bulk ingest testing

---

app/models/sipity/models/additional_attribute.rb
app/models/sipity/models/work.rb
app/repositories/sipity/commands/additional_attribute_commands.rb
db/data/20151106140726_remediate_html_entities.rb
lib/hesburgh/lib/html_scrubber.rb
spec/lib/hesburgh/lib/html_scrubber_spec.rb
spec/models/sipity/models/additional_attribute_spec.rb
spec/models/sipity/models/work_spec.rb
spec/repositories/sipity/commands/additional_attribute_commands_spec.rb

@861efbf013b7666ab19087dcd31d7fda54b3b026
Why:
* Because there are different strategies for scrubbing/sanitizing HTML
data.
@654941d119cef5eeaa1d29ee8a44e2e4a0036828
Why:
* Because we are getting all kinds of outrageous tags that have been
pasted from Word (and the RTE).
This change addresses the need by:
* Catching all "additional attributes" and the title of the work.
@91c993882855a2491b404c4a66a6471c8f8b2a33
Though I had a feeling the scrubber would behave this way, I wanted to
be certain.
@640ae7e2e93e29f08e795c325bacc8430ee2bf5e
Why:
* Because we have overly chatty HTML in our database. Prior commits
handle scrubbing at the point of persistence; However it does not
account for the data that has already been persisted.

Adding html scrubbing for data

---

app/data_generators/sipity/data_generators/work_types/etd_generator.rb
db/data/20150909173721_migration_to_include_cataloging_workflow.rb
db/schema.rb
spec/repositories/sipity/queries/processing_queries_spec.rb

@1751114f0fbc8f6bdee68ea05dd952a101f3d14e
Because at this point in time, we have marked objects as ready for
ingest; However they are not ready as they need to either go through
cataloging or be marked as ready for immediate ingest with delayed
cataloging.
The plan is to change the data migration, which has yet to run, to
move items from Ready for Ingest to the temporary, though more
appropriate 'grad_school_approved_but_waiting_for_routing'.
@fa5cb37a243087e9f736babb845eaee0e2d27505

Adding intermediary state for etd catalogin

---

app/repositories/sipity/queries/additional_attribute_queries.rb
spec/repositories/sipity/queries/additional_attribute_queries_spec.rb
spec/support/sipity/command_repository_interface.rb
spec/support/sipity/query_repository_interface.rb

Because sometimes I want just one attribute and other times I'll want
many. This puts the declaration on the form that calls the method. It
also moves towards a more expressive design.

Adding cardinality to work attribute queries.

---

app/presenters/sipity/controllers/creator_presenter.rb
app/presenters/sipity/controllers/work_submissions/show_presenter.rb
app/views/sipity/controllers/work_submissions/show.html.curly
spec/presenters/sipity/controllers/creator_presenter_spec.rb
spec/presenters/sipity/controllers/work_submissions/show_presenter_spec.rb

Prior to this commit, there was no information related to who created
the given work submission. This is a necessary field for anyone
cataloging the given work, and is helpful for people reviewing the
data.

Adding creator to the show page

---

Gemfile
Gemfile.lock
app/jobs/sipity/jobs/etd/bulk_ingest_job.rb
spec/jobs/sipity/jobs/etd/bulk_ingest_job_spec.rb

A better solution than what I had proposed was accepted. So now
Airbrake's updated version handles any attempts to close an already
closed file.
See airbrake/airbrake#426 for further reference.

Updating Airbrake dependency

---

app/controllers/sipity/controllers/work_submissions_controller.rb
app/exporters/sipity/exporters/etd_exporter.rb
app/forms/sipity/forms/work_submissions/etd/ingest_completed_form.rb
app/forms/sipity/forms/work_submissions/etd/submit_for_ingest_form.rb
config/application.yml
config/initializers/figaro.rb
spec/controllers/sipity/controllers/work_submissions_controller_spec.rb
spec/exporters/sipity/exporters/etd_exporter_spec.rb
spec/forms/sipity/forms/work_submissions/etd/ingest_completed_form_spec.rb

@a3fa52ae0e02a4c7be801c4ea3e6a783c3a17f6d
I need a way for the batch ingester to be treated as an authorized
user. This authorization is important for the bulk ingest job that
issues a WEBHOOK upon completion.
@5e32087ad8f6dac973591289e52f8ae140591e87
This works with positional variables (i.e. `def foo(var1, _var2)`), but not
with keyword variables. So instead of an explicit, yet ignored, keyword
variable have the `**keywords` kargs swallow the possible `attributes:`
keyword.
@10bf250252691087ce87e5cff5222deea8980674
I need a state advancing form that has no frills. Its purpose is to
provide a common entry point for marking something as ingested.
@e11986d004fa9748d99ebaff70fe4881cc54b32b
I'm hacking in HTTP basic authentication behavior. This is a hard-coded
and rather ugly solution. I'm …

Adding batch ingester handling

---

app/controllers/sipity/controllers/work_submission_callbacks_controller.rb
app/controllers/sipity/controllers/work_submissions_controller.rb
app/exporters/sipity/exporters/etd_exporter.rb
app/forms/sipity/forms/work_submissions/etd/ingest_completed_form.rb
config/routes.rb
spec/controllers/sipity/controllers/work_submission_callbacks_controller_spec.rb
spec/controllers/sipity/controllers/work_submissions_controller_spec.rb
spec/exporters/sipity/exporters/etd_exporter_spec.rb
spec/forms/sipity/forms/work_submissions/etd/ingest_completed_form_spec.rb
spec/routing/work_submission_routing_spec.rb

When I went to test the behavior in the integration environment, I
encountered the following exception; This exposed a few cases I did not
consider:
1. CSRF protection needs to be turned off
2. There is more than one callback that is issued during the processing
a. processing
b. success
3. The callback payload is not quite configured in the same way as the
application is expecting
So changes have been made by adding a custom callback route and
controller. This means the original work submission controller does
not have a current need for HTTP Authentication check. I have also
kept the scope of callbacks to exclude GET requests. I must also
account for specific shape of the callback.
And I must not allow a callback of job_state: 'processing' to update
the work's processing state to …

Adding WorkSubmissionCallbacks handling

---

lib/hesburgh/lib/html_scrubber.rb
spec/lib/hesburgh/lib/html_scrubber_spec.rb

In the case of Dates being persisted, the HTML scrubbing was throwing
an exception. I'm instead adding a few short circuit options to avoid
this nasty exception.
Fixes https://errbit.library.nd.edu/apps/55280e706a6f68a6d2090000/problems/5653714c6a6f687909ab0200

Adding guard clause for auto HTML scrubbing

---

app/data_generators/sipity/data_generators/email_notification_generator.rb
app/data_generators/sipity/data_generators/work_types/etd_generator.rb
app/data_generators/sipity/data_generators/work_types/ulra_generator.rb
app/models/sipity/models/notification/notifiable_context.rb
app/parameters/sipity/parameters/notification_context_parameter.rb
db/data/20151202183937_removing_submit_for_review_from_ulra.rb
db/schema.rb
spec/data_generators/sipity/data_generators/email_notification_generator_spec.rb
spec/data_generators/sipity/data_generators/work_types/ulra_generator_spec.rb
spec/models/sipity/models/notification/notifiable_context_spec.rb
spec/parameters/sipity/parameters/notification_context_parameter_spec.rb
spec/repositories/sipity/queries/notification_queries_spec.rb

@f99aa72a0c660617612a326316a55d71d981203f
Instead of repeat of knowledge extract a common variable name.
@f8181ae9c8149e0991d85b3dfa2f023f0dc657e7
Instead of having two different todo items within the workflow, I'm
opting to have students choose to sign off and faculty. This sends the
work into an interstitial state that the other person can work on.
To see the effect of this, compare the before and after processing
diagrams.
To get the processing diagram for this commit use the following:
```console
$ rake bootstrap
$ rails r scripts/commands/generate_state_machine_diagrams.rb
$ open artifacts/state_machines/ulra_submission_processing.dot -a Graphviz
```
Related to #949
@fc725447df6f8694b5af63212a4db4edebb92d07
[skip ci]
@a688e7af3032151305b889b5d9fa8d9d9eec19e9
Instead of allowing any …

ULRA workflow modeling

---

.hound.yml
app/exceptions/sipity/exceptions.rb
app/mailers/sipity/mailer_builder.rb
app/mailers/sipity/mailers/etd_mailer.rb
app/mailers/sipity/mailers/ulra_mailer.rb
app/views/sipity/mailers/etd_mailer/advisor_requests_change.html.erb
app/views/sipity/mailers/etd_mailer/advisor_signoff_is_complete.html.erb
app/views/sipity/mailers/etd_mailer/cataloger_request_change.html.erb
app/views/sipity/mailers/etd_mailer/confirmation_of_advisor_signoff.html.erb
app/views/sipity/mailers/etd_mailer/confirmation_of_advisor_signoff_is_complete.html.erb
app/views/sipity/mailers/etd_mailer/confirmation_of_grad_school_signoff.html.erb
app/views/sipity/mailers/etd_mailer/confirmation_of_submit_for_review.html.erb
app/views/sipity/mailers/etd_mailer/confirmation_of_work_created.html.erb
app/views/sipity/mailers/etd_mailer/grad_school_requests_cataloging.html.erb
app/views/sipity/mailers/etd_mailer/grad_school_requests_change.html.erb
app/views/sipity/mailers/etd_mailer/release_suspended_catalog_record.html.erb
app/views/sipity/mailers/etd_mailer/request_change_on_behalf_of.html.erb
app/views/sipity/mailers/etd_mailer/respond_to_advisor_request.html.erb
app/views/sipity/mailers/etd_mailer/respond_to_grad_school_request.html.erb
app/views/sipity/mailers/etd_mailer/submit_for_review.html.erb
app/views/sipity/mailers/ulra_mailer/confirmation_of_submitted_to_ulra_committee.html.erb
app/views/sipity/mailers/ulra_mailer/confirmation_of_ulra_submission_started.html.erb
app/views/sipity/mailers/ulra_mailer/faculty_assigned_for_ulra_submission.html.erb
app/views/sipity/mailers/ulra_mailer/faculty_completed_their_portion_of_ulra.html.erb
app/views/sipity/mailers/ulra_mailer/student_completed_their_portion_of_ulra.html.erb
spec/exceptions/sipity/exceptions_spec.rb
spec/mailers/sipity/mailer_builder_spec.rb
spec/mailers/sipity/mailers/etd_mailer_spec.rb
spec/mailers/sipity/mailers/ulra_mailer_spec.rb

@dcef535714384c07284ef5161278314fb4dc75f8
This resolves the first pass of the ULRA emails. Its enough to see what
is sent and when.
@47f2545b59230c2be5f52580096c999f78b8242e
@6244f6c931917947f6d20c10e9f4b890ad91b19f
Prior to this commit the EtdMailer had a heavy load of duplicate logic.
It wasn't as declarative as it could be.
This commit extracts a builder method that allows for the predictable
generation of the EtdMailer and an upcoming UlraMailer object. The
predictability is desirable from an validation and proper composition
stand point.
It should be noted that a few oddities are introduced with the builder,
namely the view paths in partials gets rather weird (i.e. see comments
in the builder for more details).
By extracting a function responsible for building the emailer in a …

ULRA emails that need to be sent

---

app/parameters/sipity/parameters/handled_response_parameter.rb
app/repositories/sipity/queries/additional_attribute_queries.rb
app/repositories/sipity/queries/submission_window_queries.rb
app/repositories/sipity/queries/ulra_queries.rb
app/repositories/sipity/query_repository.rb
app/validators/open_for_starting_submissions_validator.rb
spec/parameters/sipity/parameters/handled_response_parameter_spec.rb
spec/repositories/sipity/queries/additional_attribute_queries_spec.rb
spec/repositories/sipity/queries/submission_window_queries_spec.rb
spec/repositories/sipity/queries/ulra_queries_spec.rb
spec/support/sipity/command_repository_interface.rb
spec/support/sipity/query_repository_interface.rb

@0bf5ddca105caeb7e7587460e1f74a5a6395cb29
In thinking about rendering options, I have a concept of "core" for the
various processing entities (WorkArea, SubmissionWindow, and Work).
These concepts provide for rendering specific templates, forms, and
presenters yet falling back on general (i.e. core) presenters when a
specific object is not found.
I'm trying to resolve issue #957 through exploratory refactoring.
@ebb127203150146b0c195a61c78a3d3fbf0fa5f0
While it is possible this method would exist across multiple work
areas, I'd like to keep the logic separated for the time being.
@528c57b718a6271c35cee8c1825bdff3f76da0a4
As the method implies, this method finds open submission windows based
on the given date. Consider that the business logic is distributed
across the Repository and the …

Refactor work area presenter lookup

---

app/views/sipity/mailers/ulra_mailer/_important_dates.html.erb
app/views/sipity/mailers/ulra_mailer/_questions_and_about_ulra.erb
app/views/sipity/mailers/ulra_mailer/confirmation_of_submitted_to_ulra_committee.html.erb
app/views/sipity/mailers/ulra_mailer/confirmation_of_ulra_submission_started.html.erb
app/views/sipity/mailers/ulra_mailer/faculty_assigned_for_ulra_submission.html.erb
app/views/sipity/mailers/ulra_mailer/faculty_completed_their_portion_of_ulra.html.erb
app/views/sipity/mailers/ulra_mailer/student_completed_their_portion_of_ulra.html.erb
app/views/sipity/mailers/ulra_mailer/student_has_indicated_attachments_are_complete.html.erb
config/locales/en.yml

@4339ee0bc3edda55f873b36395d8c6cd0dace903
The email, as decided by the ULRA committee, has been transcribed from
their notes.
@4ab81146e37de3ab8b4f716cbaf1967f47223717
This information is used across several emails, so I'm extracting a
partial.
@09176f48c58826c815099ff95eec4a030241cd31
In the documents that I'm working from, I forgot to account for font
weight.
@f55984090a6ca51de6cb18ac708f1b8214f2d487
The email, as decided by the ULRA committee, has been transcribed from
their notes.
@21247fd558fda9b2624b821dd8c7b3599203187d
The email, as decided by the ULRA committee, has been transcribed from
their notes.
@aa6e4b4d1c912df307b25ce029df24f5c319453b
The email, as decided by the ULRA committee, has been transcribed from
their notes.
@a1f2fc0030e53eeefa34f15dc27bf10ce463db95
The email, as …

ULRA Emails

---

app/data_generators/sipity/data_generators/work_types/etd_work_types.config.json
app/forms/sipity/forms/work_submissions/etd/cataloging_complete_form.rb
app/forms/sipity/forms/work_submissions/etd/grad_school_final_signoff_form.rb
config/initializers/power_converters.rb
spec/config/initializers/power_converters_spec.rb
spec/forms/sipity/forms/work_submissions/etd/cataloging_complete_form_spec.rb
spec/forms/sipity/forms/work_submissions/etd/grad_school_final_signoff_form_spec.rb

@c910f32c6bba78baa1aa7d10841bbd435bf34d3e
We didn't need the catalogers to agree to the update.
And we wanted to provide information for them.
@c797a7eabf3815eafe0a3839f0c3eda54bbeb0c8
@229c9bc97d96f7021a01e958cd7aa786f77a5df5
The action "send_to_cataloging" did not make sense to be available in
the "ready_for_cataloging" state.
@cf6d4aa406d913bc6616d726eb673f9c266d5a81
Based on the data schema, an action may only transition to one state.
So I need an interstitial action.
@bc3726019dd70c09d40522aec6cb63007d0388ff
Prior to this commit, all "Grad School Signoff" requests would
sequester the data into a holding state. This was necessary as part of
the migration to Cataloging using Sipity.

Updates for etd changes

---

config/initializers/power_converters.rb
spec/config/initializers/power_converters_spec.rb
spec/forms/sipity/forms/work_submissions/etd/cataloging_complete_form_spec.rb

A weird scenario in which the value "004316606" was converted to
"001154438". Not sure why, but I'm adding a guard condition for that
scenario.

Fixing catalog system number coercion

---

db/data/20160217141830_add_authorname_to_etd.rb
db/schema.rb

If there are Masters' Theses or Doctoral Dissertations that do not have an `author_name` field create the field and populate it with the name of the creating user.

Remediating ETD author names

---

app/views/sipity/controllers/work_areas/etd/show.html.curly
app/views/sipity/controllers/work_areas/ulra/show.html.curly

Previously pagination controls were not contained in a column.

Moving pagination controls into their own row

---

app/mappers/sipity/mappers/etd_mapper.rb
app/mappers/sipity/mappers/generic_file_mapper.rb
config/application.yml
config/initializers/figaro.rb
spec/mappers/sipity/mappers/etd_mapper_spec.rb
spec/mappers/sipity/mappers/generic_file_mapper_spec.rb

@0acb10f162f82c94251540a1706a0f116951c5b8
It appears that CurateND has two entries related to group editors. One
in the RELS-EXT datastream and the other in the rightsMetadata
datastream. The one that appears to affect some of the CurateND
permissions is the rightsMetadata stream.
Ingested via the data migration process. The grad school can edit this
work (please note the PIDs redacted):
```xml
<rightsMetadata xmlns="http://hydra-collab.stanford.edu/schemas/rightsMetadata/v1" version="0.1">
<copyright>
<human type="title"/>
<human type="description"/>
<machine type="uri"/>
</copyright>
<access type="discover">
<human/>
<machine/>
</access>
<access type="read">
<human/>
<machine>
<group>public</group></machine>
</access>
<access type="edit">
<human/>
<machine> …
```

Fixing etd rights metadata export

---

app/exporters/sipity/exporters/batch_ingest_exporter.rb

* Favor using the attr_writer method instead of using an instance
variable. By leveraging a setter method, we can add an interface
check when we attempt to set the work. We also don't rely on internal
state of the object but instead prefer to consume the internal API of
that object.
* Privatize access to the `work` object. It does not appear that `work`
is referred to elsewhere. Keeping the exposed methods to a minimum
allows for greater flexibility later on. (i.e. you are not committing
to any more of the public interface than required)
* Replace `work.id` with `#work_id`. This is a move for greater
consistency in method usage.
Question does the privatization mean we should be passing the
exporter's work as a parameter? Or should we leave it exposed?

Adding minor revisions to BatchIngestExporter

---

app/exporters/sipity/exporters/batch_ingest_exporter.rb
spec/exporters/sipity/exporters/batch_ingest_exporter/directory_mover_spec.rb

Implementing a small module that governs the last step of the batch ingest preparation. It wraps methods from FileUtils with additional context.

#971 DirectoryMover module

---

app/repositories/sipity/queries/collaborator_queries.rb
app/repositories/sipity/queries/work_queries.rb
app/runners/sipity/runners/comment_runners.rb
spec/runners/sipity/runners/comment_runners_spec.rb

@4e59d1e2fb144793a7df1fcdd3eb89c4410c122f
[skip ci]
@8279b26698aad9f4259b5abbbe4507ac3f5b39c0
The method was already a wrapper for another method. I'm preferring, to
instead pass keyword arguments.

Minor tweaks

---

app/decorators/sipity/decorators/dashboard_view.rb
app/repositories/sipity/queries/work_queries.rb
spec/decorators/sipity/decorators/dashboard_view_spec.rb
spec/repositories/sipity/queries/work_queries_spec.rb
spec/support/sipity/command_repository_interface.rb
spec/support/sipity/query_repository_interface.rb

Tidying up the #find_works_for todo item (see below).
> Refactor places that use #find_works_for to leverage
> #find_works_via_search

Replacing #find_works_for with versatile method

---

app/repositories/sipity/command_repository.rb
app/repositories/sipity/query_repository.rb

@07a42bba96f30b1f2629a3c768f2a927ad100bdb
There are times when I forget to include the correct modules for
commands. This is a refactor to auto-include modules.
@2e3e3559bf4ec35c340be36e25a3d3cba09ae7fc
There are times when I forget to include the correct modules for
queries. This is a refactor to auto-include modules.
@34b91b86cf8df2f5a1f88ee8ec19a7dabbfb1a8e
While yes, the repository interacts with state, the object that
does the interaction should not track state, but instead require method
parameters.
[skip ci]

Favor auto load of modules

---

app/repositories/sipity/queries/work_queries.rb
spec/repositories/sipity/queries/work_queries_spec.rb
spec/support/sipity/command_repository_interface.rb
spec/support/sipity/query_repository_interface.rb

The alternate is to leverage `.find_work_by`. Its a better solution
because often when a work must be found we need additional related
information.

Removing deprecated `.find_work` method

---

app/response_handlers/sipity/response_handlers.rb
app/response_handlers/sipity/response_handlers/submission_window_handler.rb
app/response_handlers/sipity/response_handlers/work_area_handler.rb
app/response_handlers/sipity/response_handlers/work_submission_handler.rb
spec/response_handlers/sipity/response_handlers/submission_window_handler_spec.rb
spec/response_handlers/sipity/response_handlers/work_area_handler_spec.rb
spec/response_handlers/sipity/response_handlers_spec.rb

Favoring the specific context (i.e. `.for_controller`) instead of the
more general `.call` method.

Removing deprecated method

---

Gemfile

According to [bumbler](https://github.com/nevir/Bumbler) I shaved off ~740ms of development environment load time by not requiring rubocop in the Gemfile .

Not requiring rubocop decreases load times by >700 ms

---

Gemfile
Gemfile.lock

I like that bumbler can help us find the slow load times.
`bundle exec bumbler` tells us what is performing lots of requires.

Adding bumbler to the doc bundle group

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

@36b207fde0b63589b71058dc90845928f9514119
While useful, this is something that has not been leveraged throughout
the code. It was brought along as part of the rails generator template.
@b31e717c65fb58c6c2a2e54cb3f89a373758effa
I have not used this in the past years, instead falling back to console
logging. I don't know if others have used it.
@90a55b51a8faa54e67a28a80376c03691e8fa407
If you need this, go ahead and require it as part of your debugging
process.
@31edb5ca57804ba0614e650136ad260165e9fa05
We don't need it on a Rails load for all environments.
@c67ebc2aeed9ed1788e7cb5b670e1031881bdf14
Its being loading during the support process.

Removing gem dependencies

---

app/data_generators/sipity/data_generators/work_types/etd_work_types.config.json
app/presenters/sipity/controllers/debug_role_presenter.rb
app/views/sipity/controllers/work_submissions/debug.html.curly
spec/presenters/sipity/controllers/debug_role_presenter_spec.rb

@81e5162bbbf1430a3df730145b2d82999dd2b3db
There was a name change to consolidate the batch ingest process to use
the same Batch Ingestor group name across multiple work areas. See
commit @1e860fd2714627700ceb0c556c690e45c6f32c01.
This was added to the Master's Thesis work flow but not to the Doctoral
Dissertation workflow. That information is now being added.
@4e39ce65ef91f179997c07000b859e35603e17f4
As part of the trouble shooting, I needed to see what groups were
assigned. The debug form assists with that information. By adding the
model name to the page, I can be certain what model to query for
additional information.

Fixing curate ingesting not firing cataloging

---

.hound.yml
app/controllers/sipity/controllers/work_submission_callbacks_controller.rb
spec/controllers/sipity/controllers/work_submission_callbacks_controller_spec.rb

Since deploying the Sipity v2016.16 (or the day after), the webhook
callbacks have been firing from the batch ingester, but were not being
processed via the callback mechanism.
After some debugging, the WEBHOOK posting was coming as part of the
request's raw body (as per the documentation).
I ran the test I wrote against the v2016.16 codebase, and the test
failed. So something odd has happened.
Regardless, this code change now accounts for data posted as both
query parameters and request raw body.
Also adding a hound/rubocop exclusion for method complexity; This is a
compact method that is doing a few things, but I believe it remains
legible.

Updating Sipity callback handling of request body

---

app/decorators/sipity/decorators/dashboard_view.rb

The previous version looped twice through the returned array. The
updated version leverages SQL's uniqueness and sorting options thus
removing the need to iterate twice through the returned array.
This was detected through `Rubocop 0.40.0`'s suggestion of moving
`.uniq` to before the `.pluck(:name)`. It does require a bit of
reworking but Huzzah for less redundant looping through arrays.

Reducing iterations through an array

---

config/initializers/airbrake.rb

The following exception shows up with some occassion:
```ruby
URI::InvalidComponentError
```
It is the result of the following command:
```console
curl -X GET -H 'User-Agent: Netcraft SSL Server Survey - contact info@netcraft.com' https://_/
```

Ignoring weird URI exceptions

---

Gemfile
Gemfile.lock
Rakefile
config/initializers/airbrake.rb
spec/support/capybara.rb

@7753668a5d469ac75e95bef3da31fb5b910c45f1
The following exception shows up with some occassion:
```ruby
URI::InvalidComponentError
```
It is the result of the following command:
```console
curl -X GET -H 'User-Agent: Netcraft SSL Server Survey - contact info@netcraft.com' https://_/
```
@1d0bfa8c36b1c164fbd465785cb9af4215218754
This goal is set as part of Commitment; So we no longer need to include
this task.
@5f2345f2bb3fd81e12c794aa730fb3008b3177f4
While a nice consideration it is not something that I have run in the
past year, so I'm opting to remove it.

Tidying up rakefile

---

app/conversions/sipity/conversions/to_rof/work_converters/etd_converter.rb
config/locales/en.yml

CurateND used Master's Thesis, while Sipity used Master’s Thesis. This
discrepancy caused a split in the work type facet. Since the majority of the
items were using Curate's method, the decision was made to modify it in Sipity.
Data migration will still be needed on the 47 items that were using this apostrophe.

Standardize character used for apostrophe

---

app/processing_hooks/sipity/processing_hooks/etd/works/access_policy_processing_hook.rb
app/views/sipity/controllers/work_submissions/etd/access_policy.html.erb
spec/processing_hooks/sipity/processing_hooks/etd/works/access_policy_processing_hook_spec.rb

Given that our ETDs are cataloged and pointing to Curate, we want to
have that information visible in CurateND.
DLTP-530

Forcing Open Access for ETD metadata

---

app/exceptions/sipity/exceptions.rb
app/forms/sipity/forms/work_submissions/core/ingest_completed_form.rb
spec/forms/sipity/forms/work_submissions/core/ingest_completed_form_spec.rb

Prior to this commit, I was only handling the happy case. However, we
had silent failures in the batch ingest (in part because the batch
ingest does not report any errors, instead relying on silent logging
of work that failed).
DLTP-576

Notifying Airbrake when batch ingest fails

---

config/deploy.rb
scripts/copy_secrets.sh
scripts/update_secrets.sh

We are changing how secrets get injected into the Sipity application environment.
1. Start Jenkins job
2. Start the Capistrano deployment
3. Check out the secret repo on the app server
4. Copy the secrets out of the repo into the release directory
5. Capistrano completes deployment
6. Jenkins job completes
1. Start Jenkins job
2. Copy latest Sipity-specific secrets to shared directory set up by Capistrano, see `scripts/copy_secrets.sh`. There is some question about how exactly these files will be updated on the Jenkins server. For now, there will be a touch point with ESU when they need to be changed.
3. Run Capistrano deployment. Early in this process `scripts/update_secrets.sh` copies the secret files from the `shared_path` to the `release_path`.
4. Jenkins job completes
@ialford & …

New secrets management

---

app/jobs/sipity/jobs/core/bulk_ingest_job.rb
app/parameters/sipity/parameters/search_criteria_for_works_parameter.rb
app/repositories/sipity/queries/processing_queries.rb
spec/parameters/sipity/parameters/search_criteria_for_works_parameter_spec.rb

ee725aad61abb35a0dfc1287e1787e45319dc197
For Kaminari to work with per page, there is a method call temporal
dependency. First you must call `.page` then you may call `.per`.
The processing query was violating the temporal interface. Below is
the method calls from [the source code][source_code]
```ruby
scope = scope.order(criteria.order) if criteria.order?
scope = scope.page(criteria.page) if criteria.page?
scope = scope.per(criteria.per) if criteria.per?
scope
```
Prior to this change, the `:page` for criteria parameters was nil,
meaning that `scope = scope.page(criteria.page) if criteria.page?` was
skipped. However `:per` was set, and thus
`scope = scope.per(criteria.per) if criteria.per?` was called. This
resulted in a method missing error.
The fix is to amend the batch ingester method …

Fixing batch ingester

---

app/repositories/sipity/commands/permission_commands.rb
app/repositories/sipity/commands/work_commands.rb
app/services/sipity/services/manage_collaborators.rb
app/services/sipity/services/revoke_processing_permission.rb
spec/repositories/sipity/commands/permission_commands_spec.rb
spec/repositories/sipity/commands/work_commands_spec.rb
spec/services/sipity/services/manage_collaborators_spec.rb
spec/services/sipity/services/revoke_processing_permission_spec.rb
spec/support/sipity/command_repository_interface.rb

214cad70528161ae73a8ecfedd9be5214b0ee709
In the comments, I was following a recommended TODO item: extracting a
service class. I think that this extraction helps:
* tidy up the public interface of the Repository modules
* isolate the logic related to managing and assigning collaborators
* create the space for resolving the DLTP-974 issue (e.g. When
advisor's role changes need to synchronize processing permissions)
Note: this commit does not resolve DLTP-974, but instead makes it
easier to resolve.
24e481d85f1e95cc13b54b3ddc51e22ebdd787a3
From the originating DLTP-971 issue:
Reported issue:
> I know I need to contact the external research director for an
> approval, but can you look into why the committee member received a
> sign-off request email? I don't think she was supposed to — she …

Dltp 974 advisor role change

---

app/data_generators/sipity/data_generators/submission_windows/ulra_submission_windows.config.json
app/views/sipity/mailers/ulra_mailer/_important_dates.html.erb

703f32f5a9481f73a70fdf2a10834606d037de7f
Following the pattern for 2017's important dates cb30e88ff607ca831fd738aad28f132db255ee82,
this commit updates the email template for 2018.
Related to DLTP-1270
ffe2212bceaa7ebbb028de832ac04a9080c8086f
Following the established pattern of SHA1 68751a7c46ba8764a154f3b29deb0d63a78e2fe6,
this commit adds the necessary submission window information for ULRA
2018.
Related to DLTP-1270

Dltp 1270 updating for ulra 2018

---

app/presenters/sipity/controllers/work_areas/core/show_presenter.rb
spec/presenters/sipity/controllers/work_areas/core/show_presenter_spec.rb

Sipity had properly configured [processing queries][processing_queries],
however when I was setting the search criteria, I overlooked setting the
submission window (see ea3e35be7b8b454b904e9e1dcc28f5f453d58a85 for
further details on the work that was done)
DLTP-1252
[processing_queries]:https://github.com/ndlib/sipity/blob/ec8204b3984f25661cda2da35fe93da10184fe66/app/repositories/sipity/queries/processing_queries.rb#L557-L569

Ensuring submission window is passed for filter

---

README.md
app/decorators/sipity/decorators/dashboard_view.rb
app/parameters/sipity/parameters/search_criteria_for_works_parameter.rb
lib/tasks/development.rake
spec/parameters/sipity/parameters/search_criteria_for_works_parameter_spec.rb

eaae37e27fe26f55a325288964f627a16b65e47f
As I'm interested in having some rudimentary, albeit not very diverse,
data, I wanted to write up methods for seeding data.
1b1ca5ead28f3479fe3bd6d493c81d404f9f27b4
There are underlying slowness on the index page due to the flexible data
structure of Sipity and not a direct consideration for the data-
structure necessary for rendering an index view instead of a show page.
This is a quick fix meant to address DLTP-967. If the reduced pagination
does not improve the apparent responsiveness, we'll need to look into
additional measures (e.g. define the data-structure and populate that
with query results)

Dltp 967 remediate slow dashboard

---

app/views/sipity/mailers/etd_mailer/_etd_submission_assistance.html.erb

The graduate school cutover a new website (Congratulations!). With that
cutover the previous URL was redirected to the updated URL. The grad
school, not wanting to maintain too many of those, asked for the URL to
change within Sipity.
DLTP-1543

Updating graduateschool URL to reflect new website

---

app/forms/sipity/forms/work_submissions/etd/administrative_unit_form.rb
app/views/sipity/controllers/work_submissions/etd/administrative_unit.html.erb
spec/forms/sipity/forms/work_submissions/etd/administrative_unit_form_spec.rb

Change Sipity form to allow selection and display of multiple administrative units.
Completes https://jira.library.nd.edu/browse/DLTP-1594

Allow multiple administrative units

---

app/views/sipity/controllers/work_submissions/etd/administrative_unit.html.erb
spec/forms/sipity/forms/work_submissions/etd/administrative_unit_form_spec.rb

Simple-form with multiple entry elements adds an empty element at the beginning of the array. Converting admin unit to multi-element requires hiding the blank element.
See https://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-select
Related to https://jira.library.nd.edu/browse/DLTP-1594

Clean blank element in Admin Unit array

---

app/models/sipity/models/additional_attribute.rb

Relates to https://jira.library.nd.edu/browse/DLTP-1427
Predicate `organization` is unused. Removing it here allows for the removal of the corresponding json file from locabulary.

Clean up organization name

---

Gemfile
Gemfile.lock

```console
$ bundle exec rails console production
$PATH/lib/rails/commands/console.rb:2:in `require': cannot load such file -- irb (LoadError)
from $PATH/lib/rails/commands/console.rb:2:in `<top (required)>'
from $PATH/lib/rails/commands/commands_tasks.rb:123:in `require'
from $PATH/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
from $PATH/lib/rails/commands/commands_tasks.rb:58:in `console'
from $PATH/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
from $PATH/lib/rails/commands.rb:17:in `<top (required)>'
from bin/rails:34:in `require'
from bin/rails:34:in `<main>'
```

Adding "irb" gem

---

README.md
app/exporters/sipity/exporters/batch_ingest_exporter/api_file_utils.rb

The command was sending the pdf file with the token attached as part of it. The change keeps the token separate.
Fixes DLTP-1611 garbled pdf issue

Modify RestClient put_file

---

Gemfile
Gemfile.lock

Instead of referencing master, opting for an explicit SHA. Even though
the explicit SHA is part of the Gemfile.lock, it provides greater
clarity on what version of Locabulary is in use.
```console
$ bundle
```

Updating Locabulary to include latest changes

---

Gemfile.lock
app/views/sipity/mailers/etd_mailer/confirmation_of_grad_school_signoff.html.erb
app/views/sipity/shared/_accessible_objects.html.erb

Due to security vulnerability in versions under 4.6.0.
Completes https://jira.library.nd.edu/browse/DLTP-1642
The code was attempting to translate the titlized version of the `access_right_code`, which did not exist in the translation yml file.

Dltp 1642 send email

---

app/repositories/sipity/commands/administrative_commands.rb
config/environment_bootstrapper.rb
spec/repositories/sipity/commands/administrative_commands_spec.rb
spec/support/sipity/command_repository_interface.rb

When this is merged, I want to update the [dlt-ansible][1] secrets to
use the newly created repository method, as it encapsulates the
logic that keeps the secrets in-sync with the desired state.
Related to DLTP-1633
[1]:https://github.com/ndlib/dlt-ansible/

Adding command to ease group member management

---

Gemfile
Gemfile.lock
config/deploy.rb

1e06b406dc85b39500b70395eb2e74bff588fa11
In our deployment environment, I see an error (see below). I believe
this change should fix the error.
```console
cap aborted!
Capfile locked at 3.5.0, but 3.11.0 is loaded
```
03987c2f2f35263170eab84bbbd3cca0cd558918
When attempting to deploy changes via capistrano, I see the following
error:
```console
rake stderr: rake aborted!
LoadError: cannot load such file -- bigdecimal
```
In restoring bigdecimal (removed in ddb96b18b949441b1d947793f18ef5669d52da1e)
I hope to get past the blockers for Capistrano based deploys

Updating capistrano for jenkins

---

config/initializers/action_controller_parameter_hack.rb
spec/conversions/sipity/conversions/extract_input_date_from_input_spec.rb
spec/forms/sipity/forms/work_submissions/core/access_policy_form_spec.rb

In moving from Rails 4.x to 5.x, Rails adjusted the parameter object
from a HashWithIndifferentAccess to an ActionController::Parameters
object. The impact is methods that Sipity assumed no longer exist.
This hack address those issues.
In a lament, I look to all of the form objects and how creating a
simple hash to pass to them does not reflect the reality of the
application's actual behavior.
This monkey patch restores the features that I was hoping to continue
to leverage.

Addressing shift to ActionController::Parameters

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js

Prior to this commit, and since the v2019.6 release, the "Read More"
link broke; The JS function rendered the "Read More" link however the
text which should have been hidden still displayed on the page,
overlaying the content below the abstract.
I did some debugging and was unable to find a reasonable solution. In
consultation with Shari, she agreed that we could remove the "Read More"
link and instead display the entire abstract.

Removing the "Read More" abstract link

---

app/assets/javascripts/application.js
db/schema.rb

In my haste to push out a fix to the broken "Read More" / "Read Less"
behavior for abstracts, I removed code that fired the "Add another
Person" button.
This change fixes that.
In addition, in running the `rake bootstrap` command to have a fresh
environment, the `db/schema.rb` update came along. It is a rather
innocuous add.

Restoring "Add another Person" button

---

Gemfile.lock

This addresses a problem we encountered in our deploy. This was fixed in
the PR for https://github.com/sass/sassc-ruby/pull/156

Updating sassc to v2.2.1

---

app/exceptions/sipity/exceptions.rb
app/repositories/sipity/queries/work_queries.rb
config/application.rb
spec/repositories/sipity/queries/work_queries_spec.rb

Prior to this commit, when requesting a paginated list of works, the
requester would always get a 200 HTTP response when the requested page
was within the total pages for the pagination OR when the requested
page was outside the pagination range. The response document would
have an empty array of works and pagination links (self, first, last,
prev, next) as per the JSON+API specification.
In the case of one API integration, the requester appeared to follow
the following logic:
```
let page = 1
request page
while response status is 200
for each element in work array
run some process
end for
increment page by 1
request page
end while
```
The process did not appear to check that the response had any elements
in the array and stop once it encountered an empty array.
With this commit, the …

Adjusting requests outside pagination range

---

app/data_generators/sipity/data_generators/work_types/etd_work_types.config.json
app/services/sipity/services/revoke_actions_for_given_role.rb
spec/services/sipity/services/revoke_actions_for_given_role_spec.rb

Prior to this commit, the OIT's integration would see ETD works in the
Ingesting and Ingested stated. This meant that all objects that had
been approved by the Grad School were processed each time. This
resulted in at least 170 pages of data to process, and was growing each
year.
Per Grad School instructions, I'm removing access to the
ETD_INTEGRATORS for ingesting and ingested state.
From Shari:
> I don't recall the specifics. I know that it's helpful for us to have
> updates pushed to OnBase if we correct the title or advisor on the
> Sipity record before we approve it (for example). If we could set
> OnBase to stop updating a given record once the Sipity State hits
> "ingesting" that would be the best of all worlds for us.
Upon further discussion, the OnBase process has detected things …

Removing ETD_INTEGRATORS from ingested state

---

app/parameters/sipity/parameters/search_criteria_for_works_parameter.rb
spec/parameters/sipity/parameters/search_criteria_for_works_parameter_spec.rb

Prior to this commit, it appears that we had a String for page. In the
comparison introduced in SHA 5ff5ca05fffb809b47ca3d12f5f88a528308dd7b,
we introduced the bug.
This commit ensures that we are working with integers

Coercing page parameter to integer

---

app/data_generators/sipity/data_generators/work_types/etd_work_types.config.json

This undoes a portion of the "Removing ETD_INTEGRATORS from ingested
state" commit (see 3457f118ab2867c5a0ce25a35725cb3b4fc5bcef)
Based on conversations with OIT, their processes were dependent on a
full list of ETDs. With the prior change, they no longer had a full
list of ETDs, but instead had a list of ETDs that were still subject to
changes in Sipity.
This change is a temporary revert of the above commit. Based on
negotiated timelines, we have informed OIT that will remove
ETD_INTEGRATORS access to ingested state objects on March 4th 2020.

Restoring ETD_INTEGRATORS to ingested state

---

app/exporters/sipity/exporters/batch_ingest_exporter/webhook_writer.rb
spec/exporters/sipity/exporters/batch_ingest_exporter/webhook_writer_spec.rb

Alas, spaces in basic auth are not allowed. Curious how this is
showing up years later, but such is the way of technology
implementations slowly catching up with standards and their steady
drift.
This change is a stop gap. To complete the change we will need to:
1) Deploy the change
2) Update all existing published Webhooks to be URI encoded

Encoding URI's written in WEBHOOKS

---

README.md
app/controllers/sipity/controllers/visitors_controller.rb
config/routes.rb
spec/controllers/sipity/controllers/visitors_controller_spec.rb

This end-point enables a quick assessment of an object in Sipity. It
produces minimal information:
* id: the id of the object
* status: the name of the object's current processing state
As this is entirely non-identifying information, its not behind an API
end point.
Closes #1240

Adding `/status/:work_id` end point

---

app/data_generators/sipity/data_generators/work_types/etd_work_types.config.json
app/forms/sipity/forms/work_submissions/etd/submission_date_form.rb
app/views/sipity/controllers/work_submissions/etd/submission_date.html.erb
config/locales/en.yml
spec/forms/sipity/forms/work_submissions/etd/submission_date_form_spec.rb

Prior to this commit, Sipity stamped the etd_submission_date at the
point when the student submitted their work. Sipity did not then
provide a means of updating etd_submission_date (aside from using
SQL or the Rails console).
With this commit, I added a form in which the grad school can edit the
etd_submission_date.
This feature was prompted in an email thread with Shari.

Enabling Grad School editing of submission date

---

app/services/sipity/services/netid_query_service.rb
spec/services/sipity/services/netid_query_service_spec.rb

83d6b359abc756ae72b8c610994c3d74e5244651
We encountered the following error:
```shell
OpenSSL::SSL::SSLError
SSL_connect returned=1 errno=0 state=error: certificate verify failed
```
Triaging the problem, we discovered an intermittent issue that we are
working to resolve. In the mean time, I worked through this commit.
First, I adjusted the system to provide two different reader methods. I
did not want to lose sight of the "when things are working" state. I
also wanted to draw attention to the "when things aren't working" state
and how we solved that.
This commit makes the upcoming change easier. By design, I'm exposing
the workaround as an option, but with this commit continuing to use the
desired method.
e3b76c568fa82220c6d97c6d6eecb918ce2c7499
Yes, this is not ideal. However, we have a …

Addressing ssl issues

---

app/services/sipity/services/netid_query_service.rb
spec/services/sipity/services/netid_query_service_spec.rb

This reverts commit e3b76c568fa82220c6d97c6d6eecb918ce2c7499.
On Sipity PREP I have tested and verified the commit just prior to the
the e3b76c5 commit (e.g. what this commit reverts).
Once merged and deployed, Sipity will again verify SSL connections.
In using the revert, I'm hoping to keep this information around as a
reference point.

Revert "HACK - Switch NetID reader to not verify SSL"

---

spec/forms/sipity/forms/work_submissions/core/ingest_completed_form_spec.rb

Prior to this commit, the associated descriptors were incorrectly
paired with the executed body of the message.

Adjusting spec method to body match descriptor

---

app/forms/sipity/forms/work_submissions/core/ingest_completed_form.rb
spec/forms/sipity/forms/work_submissions/core/ingest_completed_form_spec.rb

Prior to this commit, there was an assumption that the IngestCompleted
form was only used to advance the state.  However, in discussion with
Don, the purpose of the WEBHOOK for the batch ingester was meant to be a
communication tool (e.g., post status to WEBHOOK when we start
processing, when there's an error, and when there's success).
Under the above batch ingester assumption, the client should not send a
422 because ERROR was invalid.  Instead, it should send a 200
status (e.g. yup, I got your message).
Future work might include reworking the form to handle routing to
different states based on the status of the WEBHOOK.  For now, this gets
things unstuck.

Reworking IngestCompleted to handle error state

---

config/routes.rb

This URL is generated via the dynamic database entries of Sipity.
However, it is a route that is invisible to most interactions.
I’m adding this to help document end points.

Adding OIT OnBase documentation

---

app/services/sipity/services/noid_minter.rb
spec/services/sipity/services/noid_minter_spec.rb

Prior to this commit, Sipity did not have a means of testing against a
running [our NOIDs server](https://github.com/ndlib/noids). This
commit refactors the specs and minter implementation to make it
possible to run an integration test against a "live" NOIDs server.
The refactor preserves the lambda method signature in the [application
config][1] for the configured default_pid_minter.
Dependent on ndlib/noids_client#5
[1]:./config/application.rb

Adding full NOIDs integration

---

app/services/sipity/services/administrative/force_into_processing_state.rb

Prior to this commit, the returned value was an empty array (e.g.,
`[]`).  That return value might lead one to think that no objects were
processed.
In returning `true`, I hope to have a more friendly (less head-scratchy)
returned value.

Improving returned value for force state change

---

app/exceptions/sipity/exceptions.rb
app/jobs/sipity/jobs/core/bulk_ingest_job.rb
spec/exceptions/sipity/exceptions_spec.rb
spec/jobs/sipity/jobs/core/bulk_ingest_job_spec.rb

Sipity is already raising an individiual exception when it fails to
"ingest" a single work.  What is missing, however, is a greater
context (and sharing of what might be happening).
In adding this new bit of logic, my hope is to include a more verbose
exception that explains: "Yup, there's an error in the bulk job, and as
a result the work's status likely didn't change.  So go look at the
details of that exception."
In other words, the presence of this newly added error says: "Hey, Batch
Ingest had a problem."

Adding NightlyJob exception handling

---

app/data_generators/sipity/data_generators/work_types/etd_work_types.config.json

Prior to this commit, the Master's Thesis had the "hurray your work"
email, but not the doctoral dissertation.
That is an oversight and this change adds that feature.

Adding "hurray" email to Doctoral Dissertation

---

config/schedule.rb

To make it a bit less messy, I went with another string method for
clarification.
The prior implementation:
```
runner "Sipity::Jobs::Core::BulkIngestJob.call(work_area_slug: 'etd',
initial_processing_state_name: 'ready_for_doi_minting',
processing_action_name: 'submit_for_doi_minting')"
```
is functionally equivalent to the new implementation:
```
runner %(Sipity::Jobs::Core::BulkIngestJob.call(work_area_slug: "etd",
initial_processing_state_name: "ready_for_doi_minting",
processing_action_name: "submit_for_doi_minting"))
```
The resulting crontab for the prior implemntation is:
```
11 1 * * * /bin/bash -l -c 'cd ~/git/ndlib/sipity &&
/usr/local/bin/bundle exec bin/rails runner -e production
'\''Sipity::Jobs::Core::BulkIngestJob.call(work_area_slug:
'\''\'\'''\''etd'\''\'\'''\'', …
```

Reducing number of hack `'` characters for crontab

---

app/presenters/sipity/controllers/visitors/etd/work_area_presenter.rb
app/presenters/sipity/controllers/work_areas/etd/show_presenter.rb
app/presenters/sipity/controllers/work_areas/filter_form_presenter.rb
app/views/sipity/controllers/visitors/etd/work_area.html.curly
app/views/sipity/controllers/work_areas/etd/show.html.curly
config/locales/en.yml
spec/presenters/sipity/controllers/visitors/etd/work_area_presenter_spec.rb
spec/presenters/sipity/controllers/work_areas/etd/show_presenter_spec.rb
spec/presenters/sipity/controllers/work_areas/filter_form_presenter_spec.rb

This addresses a number of pain-point issues identified in the following tickets:
CURATE-287 - adds search in sipity
CURATE-105 - adds another button for those not logged in so advisor's option is more clear.
CURATE-104 - adds some translations and titles for advisor approval buttons & verification views
CURATE-288 - sorting by initial submission begin date was already present, but somewhat hidden. This adds titles to the sort/select/search boxes.
note: branch is deployed on prep for review purposes.

UI Improvements

---

app/parameters/sipity/parameters/search_criteria_for_works_parameter.rb
app/presenters/sipity/controllers/work_areas/core/show_presenter.rb
app/presenters/sipity/controllers/work_areas/etd/show_presenter.rb
app/presenters/sipity/controllers/work_areas/work_presenter.rb
app/repositories/sipity/queries/processing_queries.rb
app/repositories/sipity/queries/work_queries.rb
app/views/sipity/controllers/work_areas/etd/show.html.curly
config/brakeman.yml
spec/parameters/sipity/parameters/search_criteria_for_works_parameter_spec.rb
spec/presenters/sipity/controllers/work_areas/core/show_presenter_spec.rb
spec/presenters/sipity/controllers/work_areas/etd/show_presenter_spec.rb
spec/presenters/sipity/controllers/work_areas/work_presenter_spec.rb
spec/repositories/sipity/queries/processing_queries_spec.rb

3103308adf88e67f2848d12dbc112074833326d7
I'm not certain that this will work, but I want to capture the logic
that I've done to generate the joins.
The reason that this is not quite right is that I need to add the change
into given `criteria` AND `scope_proxied_objects_for_the_user_and_proxy_for_type` method.
The `criteria` object defines what are the sort columns and query
strings; so I need to expose the field sort for that.  The
`scope_proxied_objects_for_the_user_and_proxy_for_type` creates the
initial AREL scope from which we then build out additional queries.
So, while this "kind of works" and "kind of" addresses the
situation (e.g., the product owner wants to see the author and the
submission date in the dashboard and the dashboard is too slow), it's
not yet done. …

Adding Author Name and Submission Date to Dashboard

---

app/parameters/sipity/parameters/search_criteria_for_works_parameter.rb
spec/parameters/sipity/parameters/search_criteria_for_works_parameter_spec.rb

Given the speed-ups for the dashboard (see ["Adding Author Name and
Submission Date to Dashboard" pull request][1]), we can increase the
size of pagination without impacting performance.
[1]:https://github.com/ndlib/sipity/pull/1287

Increasing dashboard paging size

---

README.md
config/database.yml

With this change, you no longer need a mysql password.
In your shell, you can add the following:
```
export SKIP_MYSQL_PASSWORD_FOR_LOCAL_DEVELOPMENT="true"
```
I added the above line to my `config/aliases.zsh`, which should
propogate through my tests.

Ensuring that we can skip mysql password

---

README.md
spec/coverage_helper.rb

059afc6b151b7a3b7bb19cb010f750a059b16423
Prior to this commit, the Github CI checks included a step that pushed
the code coverage report to CodeClimate.  After this commit, that step
is gone.
NOTE: the build will still break if we do not meet the coverage
requirements.

Removing code climate reporting

---

app/forms/sipity/forms/work_areas/core/show_form.rb
app/parameters/sipity/parameters/search_criteria_for_works_parameter.rb
app/presenters/sipity/controllers/work_areas/core/show_presenter.rb
app/presenters/sipity/controllers/work_areas/filter_form_presenter.rb
app/repositories/sipity/queries/processing_queries.rb
app/views/sipity/controllers/work_areas/etd/show.html.curly
app/views/sipity/controllers/work_areas/ulra/show.html.curly
spec/forms/sipity/forms/work_areas/core/show_form_spec.rb
spec/parameters/sipity/parameters/search_criteria_for_works_parameter_spec.rb
spec/presenters/sipity/controllers/work_areas/core/show_presenter_spec.rb
spec/presenters/sipity/controllers/work_areas/filter_form_presenter_spec.rb
spec/repositories/sipity/queries/processing_queries_spec.rb
spec/support/sipity/command_repository_interface.rb
spec/support/sipity/query_repository_interface.rb

2400ed74057e29d7067dc88e1f783618965e6882
With this commit, you can now select and filter on multiple states on
the dashboard.
4e8ce0b7caea1a51ca6c70b3b002748873d375fe
This aligns with the emerging changes for the
`SearchCriteriaForWorksParameter` interface (e.g., moving from single
value to multiple value).
3a0b76421a30487679466e15b4d7f1c16a6b45f4
Prior to this commit, the order of assignment was somewhat arbitrary.
And as I want to amend the default_processing_states to start with
non-terminal states, I need to ensure that work_area is set before the
others (so that I can query the work area's non-terminal states).
a16ec11bdf9429de594fde662f2115bcdf0c1262
Prior to this change, the parameter name presumed a singular value.
With this change, the parameter name implies plurality.
As part of …

Adding default omit terminal actions

---

app/forms/sipity/forms/work_areas/core/show_form.rb
spec/forms/sipity/forms/work_areas/core/show_form_spec.rb

Prior to this commit, the UI did not start with any processing states
selected.  Which, by default, meant include all of them in the filter.
(Notice the PREP URL with no items selected)
After this commit, the UI now defaults to the non-terminal states being
selected.
(notice the DEV URL with items selected by default)

Defaulting UI to start with only terminal states

---

app/jobs/sipity/jobs/core/bulk_ingest_job.rb

Exporters only handle one page of items. Rather than expend a large amount of time to handle pagination in the exporters, it is much easier to just override the default page size for exporter queries.
Resolves CURATE-342

Enlarge page size for exporter queries

---

Gemfile
Gemfile.lock

Before Jeremy left, he copied several repos over to the ndlib organization from his personal account that are in use by Sipity. The forks referenced below have been deleted from his personal account, so we need to update the Gemfile to point to the new location:
* https://github.com/ndlib/curly/tree/updated-sipity-hacks
* https://github.com/ndlib/data-migrator
* https://github.com/ndlib/dragonfly/tree/updating-dragonfly-to_file
* https://github.com/ndlib/railroady/tree/allowing-namespaced-models

CURATE-356 Fork repositories from Jeremy's Github account

---

app/forms/sipity/forms/work_submissions/core/ingest_completed_form.rb
app/repositories/sipity/commands/todo_list_commands.rb
app/repositories/sipity/queries/attachment_queries.rb
app/services/sipity/services/action_taken_on_entity.rb
scripts/one-offs/callback.rb
spec/forms/sipity/forms/work_submissions/core/ingest_completed_form_spec.rb
spec/repositories/sipity/commands/todo_list_commands_spec.rb
spec/repositories/sipity/queries/attachment_queries_spec.rb
spec/services/sipity/services/action_taken_on_entity_spec.rb
spec/support/sipity/command_repository_interface.rb

DAS-3027 (Related to https://github.com/ndlib/sipity/pull/1306) 
After a file is replaced and re-ingested, the "Replace File" to-do item was marked as complete, and the "Reingest File" action button is active. 
Since file replacement can be repeated multiple times, this problem is solved by removing the Entity Action Registration for "replace file" once the ingest is complete as part of the callback from batch ingest.

Use Entity Registry to track file replacements
